#!/usr/bin/env bash
set -euo pipefail

cd /workspace/tfplan2md

# Idempotency guard
if grep -qF "- When you are creating or choosing a work branch yourself, use the documented `" ".github/copilot-instructions.md" && grep -qF "**GitHub Copilot PR branch exception:** When GitHub creates a coding-agent pull " "docs/agents.md"; then
  echo "Gold patch already applied."
  exit 0
fi

git apply --whitespace=nowarn <<'PATCH'
diff --git a/.github/copilot-instructions.md b/.github/copilot-instructions.md
@@ -28,14 +28,16 @@ For project-specific instructions, refer to the `docs/spec.md` file in the repos
 - Always ensure that you have up-to-date information. Use web search if you think that your information might be outdated (example: new versions of frameworks, libraries, tools, etc.)
 - Use pre-commit hooks and linters to ensure code quality and consistency
 - Do not edit CHANGELOG.md under any circumstances; changelog entries are generated by Versionize in CI. (strict)
-- Create feature branches for all changes that follow the convention described in the documentation
+- When you are creating or choosing a work branch yourself, use the documented `feature/`, `fix/`, `workflow/`, or `website/` naming convention. If GitHub has already placed you on a coding-agent PR branch named `copilot/*`, stay on that branch; it does not override the underlying work-item or workflow convention.
 - After implementing changes, ensure that the documentation is updated accordingly
 - Use sub-agents (via the `task` tool) to reduce context rot: delegate codebase research to `explore` agents and build/test runs to `task` agents so their output stays out of your main context. Reserve your context window for the primary task. See `docs/agents.md` § Sub-Agent Strategy for the full decision matrix.
 
 ## GitHub Copilot Coding Agent Workflow (CRITICAL)
 
 **If you are running as a GitHub Copilot coding agent** (assigned issues via `@copilot`, PR coding agent on `copilot/*` branches), you **MUST** use the `report_progress` tool for all commits and pushes. **Manual `git push` commands will fail.**
 
+Treat `copilot/*` as a GitHub-managed branch name for the current PR, not as a repository workflow-naming violation. The underlying work still follows the documented feature/fix/workflow/website conventions and matching `docs/` work-item folders.
+
 **Exception — subagents spawned via `task` tool**: `report_progress` is NOT available to subagents. They must use `git commit` instead (see below).
 
 ### Why Manual Git Commands Fail
@@ -242,4 +244,4 @@ Note: `docs/agents.md` is a helpful index, but `.github/skills/` is the authorit
 			"env": {},
 			"type": "stdio"
 		}
-```
\ No newline at end of file
+```
diff --git a/docs/agents.md b/docs/agents.md
@@ -672,6 +672,8 @@ Example: If the most recent feature is `025-...` and a workflow item `026-...` a
 | Workflow Improvements | `workflow/` | `workflow/028-improvement-opportunities` | Workflow Engineer |
 | Website Changes | `website/` | `website/homepage-redesign` | Web Designer |
 
+**GitHub Copilot PR branch exception:** When GitHub creates a coding-agent pull request, it may place the work on an auto-generated `copilot/*` branch. That branch name is an execution-context detail for the existing PR, not a replacement for the underlying `feature/`, `fix/`, `workflow/`, or `website/` work-item convention. Continue to use the matching work-item folder and workflow type, and do not treat `copilot/*` by itself as a workflow violation.
+
 **Note:** The Requirements Engineer creates the feature branch at the start of the feature workflow. The Issue Analyst creates the fix branch at the start of the bug fix workflow. All subsequent agents work on the same branch until Release Manager creates the pull request.
 
 **Commit Type Guardrails:** Pull requests that only change workflow/internal tooling (`.github/`, `scripts/`, `docs/`, `website/`) must NOT use `feat:` or `fix:` commit types — use `workflow:`, `docs:`, `chore:`, `ci:`, or `refactor:` instead. Using `feat:` or `fix:` for non-code changes causes incorrect Versionize version bumps. See [docs/spec.md § Commit Guardrails](spec.md#github-actions-workflows) for details.
PATCH

echo "Gold patch applied."
