#!/usr/bin/env bash
set -euo pipefail

cd /workspace/jobset

# Idempotency guard
if grep -qF "- **Validation**: Use [CEL validation](https://kubernetes.io/docs/reference/usin" "AGENTS.md" && grep -qF "CLAUDE.md" "CLAUDE.md" && grep -qF "CLAUDE.md" "CLAUDE.md"; then
  echo "Gold patch already applied."
  exit 0
fi

git apply --whitespace=nowarn <<'PATCH'
diff --git a/AGENTS.md b/AGENTS.md
@@ -1,32 +1,62 @@
-# AGENTS.md
-
-This file provides guidance to AI assistants (Claude, Gemini, etc).
-
-## Project Overview
+## Kubernetes JobSet
 
 JobSet is a Kubernetes-native API for managing groups of Kubernetes Jobs as a unit, designed for distributed AI/ML training workloads (PyTorch, Jax, TensorFlow) and HPC applications (MPI). It is a Kubernetes SIG (Special Interest Group) project maintained under kubernetes-sigs.
 
 ## Agent Behavior Policy
 
 AI agents should:
+
 - Make atomic, minimal, and reversible changes.
-- Prefer local analysis (`make test, make build, make test-integration, make verify`) before proposing commits.
+- Prefer local analysis (`make test`, `make build`, `make test-integration`, `make verify`) before proposing commits.
+- NEVER modify CI/CD workflows or release automation unless explicitly requested.
 - Use `AGENTS.md` and `Makefile` as the source of truth for development commands.
 
 Agents must NOT:
+
 - Bypass tests or linters
-- Introduce dependencies without updating `pyproject.toml`
+- Introduce dependencies without updating `go.mod`
 - Generate or commit large autogenerated files
-
+- Modify CRD schemas or API versions without explicit instruction
 
 ### Context Awareness
 
 Before writing code, agents should:
 
 - Read existing test cases for pattern alignment
-- Preserve existing logging and error-handling conventionso
+- Match import patterns from neighboring files
+- Preserve existing logging and error-handling conventions
+- Review CRD schemas in `api/jobset/v1alpha2/` before changing API structures
+- Call out any breaking changes and follow the deprecation policy
 
-## Common Development Commands
+## Repository Map
+
+```
+jobset/
+├── api/jobset/v1alpha2/        # API types (JobSet, ReplicatedJob); edit here for API changes
+├── charts/                     # Helm Charts to deploy JobSet
+├── client-go/                  # Generated typed clientsets, informers, listers
+├── cmd/                        # Controller manager entrypoint (main.go is at root)
+├── config/                     # Kustomize manifests to deploy JobSet
+├── hack/                       # Code generation, boilerplate, deploy scripts
+├── keps/                       # Enhancement proposals for JobSet
+├── pkg/
+│   ├── config/                 # JobSet configuration ConfigMap
+│   ├── constants/              # All annotation, label, and env var key constants
+│   ├── controllers/            # JobSet and Pod reconcilers, failure/success/TTL policies
+│   ├── features/               # Feature gate definitions
+│   ├── metrics/                # Prometheus metric definitions and registration
+│   ├── util/                   # Shared utilities (collections, placement)
+│   ├── version/                # Version info
+│   └── webhooks/               # Validating and mutating webhook handlers
+├── site/                       # Hugo + Docsy documentation site
+└── test/
+    ├── e2e/                    # End-to-end tests (Kind cluster)
+    └── integration/            # envtest based integration tests
+```
+
+## Commands
+
+<!-- BEGIN: AGENT_COMMANDS -->
 
 ### Building and Testing
 
@@ -139,6 +169,8 @@ make helm-verify
 make helm-chart-package
 ```
 
+<!-- END: AGENT_COMMANDS -->
+
 ## Architecture Overview
 
 ### Core Components
@@ -159,12 +191,6 @@ make helm-chart-package
    - **Pod Mutating Webhook** (`pod_mutating_webhook.go`): Injects environment variables and configuration into Pods
    - **Pod Admission Webhook** (`pod_admission_webhook.go`): Enforces exclusive placement constraints
 
-4. **Policy Controllers**
-   - **Failure Policy** (`pkg/controllers/failure_policy.go`): Determines when to restart JobSet on failures
-   - **Success Policy** (`pkg/controllers/success_policy.go`): Determines when JobSet is complete
-   - **TTL After Finished** (`pkg/controllers/ttl_after_finished.go`): Cleanup of completed JobSets
-   - **Depends On** (`pkg/controllers/depends_on.go`): Handles dependency relationships
-
 ### API Structure
 
 - **API Version**: `jobset.x-k8s.io/v1alpha2` (`api/jobset/v1alpha2/`)
@@ -191,51 +217,98 @@ make helm-chart-package
 - **E2E Tests**: `test/e2e/` - uses real Kubernetes clusters (Kind for CI)
   - Uses Ginkgo/Gomega frameworks
 
+**Requirements:**
+
+- Every new feature or bug fix must include tests
+- Unit tests go in the same package as the source file (`*_test.go`)
+- Integration tests go in `test/integration/`
+- Use table-driven tests (map or slice of structs) for multiple scenarios
+
 ### Code Generation Tools
 
 JobSet uses multiple code generators (all invoked via `make generate`):
+
 - **controller-gen**: Generates CRDs, RBAC, and webhook configs from Go markers
 - **client-gen**: Generates typed clientsets for jobset resources
 - **openapi-gen**: Generates OpenAPI spec for API validation
 - **Python SDK generator**: `hack/python-sdk/gen-sdk.sh` generates Python client library
 
-## Important Development Notes
+## Development Workflow for AI Agents
+
+**Before making changes:**
+
+1. Read existing code patterns, comments, and tests in neighboring files
+2. Check `pkg/constants/constants.go` for annotation/label keys before defining new ones
+3. Run `make verify` to establish a clean baseline before editing
+4. Check the Core Development Principles below
+
+**Commit and PR hygiene:**
+
+- Follow the [Kubernetes commit message convention](https://www.kubernetes.dev/docs/guide/pull-requests/#commit-message-guidelines):
+  short imperative subject, blank line, then body explaining the "why"
+- Include rationale ("why") in commit messages and PR descriptions, not just "what"
+- Only modify files relevant to the task; keep diffs minimal
+- Do not push secrets or modify git config
+- Always run `make generate` after modifying the source code
+
+## Core Development Principles
+
+### API Stability ⚠️ CRITICAL
+
+JobSet's API (`jobset.x-k8s.io/v1alpha2`) is in alpha. Always preserve backward compatibility within a version.
+
+**Rules for API changes** (`api/jobset/v1alpha2/jobset_types.go`):
+
+- **Adding fields**: Use `+optional` marker and provide a default where possible
+- **Removing or renaming fields**: Requires an API version bump and a migration plan — do not do this without explicit instruction
+- **Changing field types**: Breaking change; requires a deprecation period
+- **Validation**: Use [CEL validation](https://kubernetes.io/docs/reference/using-api/cel/) (`+kubebuilder:validation:XValidation`) wherever applicable instead of webhook-only validation
+- **Always call out breaking changes** in PR descriptions and commit messages
+
+❌ **Bad — silent breaking change:**
+
+```go
+type JobSetSpec struct {
+    // Renamed without migration
+    Paused *bool `json:"paused,omitempty"`
+}
+```
+
+✅ **Good — backward compatible addition:**
+
+```go
+type JobSetSpec struct {
+    // Suspend stops the JobSet without deleting resources.
+    // +optional
+    Suspend *bool `json:"suspend,omitempty"`
+
+    // NewFeature enables experimental capability X.
+    // +optional
+    NewFeature *bool `json:"newFeature,omitempty"`
+}
+```
+
+**After any API change:**
+
+1. Add `+kubebuilder` markers for validation, defaulting, or CRD generation
+2. Run `make generate` to update generated code
+3. Run `make verify` to confirm all generated artifacts are up to date
 
 ### E2E Test Environment Variables
+
 - `KIND_CLUSTER_NAME`: Name of Kind cluster (default: "kind")
 - `USE_EXISTING_CLUSTER`: Set to "true" to test against existing cluster instead of creating new Kind cluster
 - `E2E_KIND_VERSION`: Kubernetes version for Kind cluster (default: kindest/node:v1.34.0)
 - `E2E_TARGET`: Test target pattern (default: ./test/e2e/...)
 
-### Working with APIs
-
-When modifying JobSet API (`api/jobset/v1alpha2/jobset_types.go`):
-1. Add kubebuilder markers for validation, defaulting, or CRD generation
-2. Run `make generate` to update generated code
-3. Run `make verify` to ensure all generated code is up to date
-4. The `+kubebuilder` comments are critical for CRD generation
-
 ### Webhook Development
 
 Webhooks run as part of the JobSet controller manager. When testing locally:
+
 - Webhooks require valid TLS certificates
 - Use `cert-controller` package for certificate management
 - Webhook configurations are in `config/components/webhook/`
 
 ### Metrics
 
 JobSet exposes Prometheus metrics via `pkg/metrics/`. When adding new metrics, follow the existing pattern and register them in the metrics package init function.
-
-### Important Constants
-
-Check `pkg/constants/constants.go` for:
-- Annotation keys (e.g., exclusive placement, coordinator labels)
-- Label keys (e.g., jobset name, replicated job name, job index)
-- Environment variable names injected into pods
-
-### Release Process
-
-Releases follow a 2-3 month cycle:
-1. Update version in relevant places using `make prepare-release-branch VERSION=vX.Y.Z`
-2. Generate release artifacts with `make artifacts`
-3. Release artifacts include manifests, Prometheus config, and Helm chart
diff --git a/CLAUDE.md b/CLAUDE.md
@@ -1 +0,0 @@
-@AGENTS.md
diff --git a/CLAUDE.md b/CLAUDE.md
@@ -0,0 +1 @@
+AGENTS.md
\ No newline at end of file
PATCH

echo "Gold patch applied."
