"""Behavioral checks for starfish-add-github-copilot-instructions-for (markdown_authoring task).

Each test asserts that a distinctive literal from the gold patch appears
in the target tier-1 file after the agent runs.
"""
from __future__ import annotations

from pathlib import Path

REPO = Path("/workspace/starfish")


def _read(path: str) -> str:
    p = REPO / path
    assert p.is_file(), f"{p} does not exist"
    return p.read_text(encoding="utf-8", errors="replace")


def test_signal_00():
    """Distinctive line from gold patch must be present."""
    text = _read('.github/copilot-instructions.md')
    assert '**starfish** is a Python library for processing images of image-based spatial transcriptomics. It provides scalable pipelines that localize and quantify RNA transcripts in image data generated by any ' in text, "expected to find: " + '**starfish** is a Python library for processing images of image-based spatial transcriptomics. It provides scalable pipelines that localize and quantify RNA transcripts in image data generated by any '[:80]


def test_signal_01():
    """Distinctive line from gold patch must be present."""
    text = _read('.github/copilot-instructions.md')
    assert '1. Create a new file in the appropriate directory (e.g., `starfish/core/image/Filter/new_filter.py`)' in text, "expected to find: " + '1. Create a new file in the appropriate directory (e.g., `starfish/core/image/Filter/new_filter.py`)'[:80]


def test_signal_02():
    """Distinctive line from gold patch must be present."""
    text = _read('.github/copilot-instructions.md')
    assert '2. Import the corresponding `AlgorithmBase` (e.g., `FilterAlgorithm` from `_base.py`)' in text, "expected to find: " + '2. Import the corresponding `AlgorithmBase` (e.g., `FilterAlgorithm` from `_base.py`)'[:80]

