"""Behavioral checks for hardwarevisualizer-docs-add-project-guidelines-and (markdown_authoring task).

Each test asserts that a distinctive literal from the gold patch appears
in the target tier-1 file after the agent runs.
"""
from __future__ import annotations

from pathlib import Path

REPO = Path("/workspace/hardwarevisualizer")


def _read(path: str) -> str:
    p = REPO / path
    assert p.is_file(), f"{p} does not exist"
    return p.read_text(encoding="utf-8", errors="replace")


def test_signal_00():
    """Distinctive line from gold patch must be present."""
    text = _read('.github/copilot-instructions.md')
    assert '- If OS APIs / DB / external I/O are involved, also add/change `src-tauri/src/infrastructure/**` (e.g. `infrastructure/providers/**`, `infrastructure/database/**`)' in text, "expected to find: " + '- If OS APIs / DB / external I/O are involved, also add/change `src-tauri/src/infrastructure/**` (e.g. `infrastructure/providers/**`, `infrastructure/database/**`)'[:80]


def test_signal_01():
    """Distinctive line from gold patch must be present."""
    text = _read('.github/copilot-instructions.md')
    assert '- Rust backend follows strict one-way dependencies: **Commands → Services → Platform (Factory) → OS APIs** (see `docs/ARCHITECTURE/BACKEND_ARCHITECTURE.md`).' in text, "expected to find: " + '- Rust backend follows strict one-way dependencies: **Commands → Services → Platform (Factory) → OS APIs** (see `docs/ARCHITECTURE/BACKEND_ARCHITECTURE.md`).'[:80]


def test_signal_02():
    """Distinctive line from gold patch must be present."""
    text = _read('.github/copilot-instructions.md')
    assert '- i18n: `src/lib/i18n.ts` with `src/lang/en.json` and `src/lang/ja.json`. Add UI strings to JSON and reference via `useTranslation()` (e.g. `src/App.tsx`).' in text, "expected to find: " + '- i18n: `src/lib/i18n.ts` with `src/lang/en.json` and `src/lang/ja.json`. Add UI strings to JSON and reference via `useTranslation()` (e.g. `src/App.tsx`).'[:80]


def test_signal_03():
    """Distinctive line from gold patch must be present."""
    text = _read('AGENTS.md')
    assert 'Frontend ↔ backend communication is done via **Tauri commands**; TypeScript bindings are generated (see `src/rspc/bindings.ts`, do not edit manually).' in text, "expected to find: " + 'Frontend ↔ backend communication is done via **Tauri commands**; TypeScript bindings are generated (see `src/rspc/bindings.ts`, do not edit manually).'[:80]


def test_signal_04():
    """Distinctive line from gold patch must be present."""
    text = _read('AGENTS.md')
    assert '- Generated bindings: `src/rspc/bindings.ts` is generated by tauri-specta; edit Rust commands and re-run `npm run tauri dev` to regenerate.' in text, "expected to find: " + '- Generated bindings: `src/rspc/bindings.ts` is generated by tauri-specta; edit Rust commands and re-run `npm run tauri dev` to regenerate.'[:80]


def test_signal_05():
    """Distinctive line from gold patch must be present."""
    text = _read('AGENTS.md')
    assert '- Error events: backend emits `error_event`; frontend listens via `useErrorModalListener` in `src/hooks/useTauriEventListener.ts`.' in text, "expected to find: " + '- Error events: backend emits `error_event`; frontend listens via `useErrorModalListener` in `src/hooks/useTauriEventListener.ts`.'[:80]

