"""
Tests for TanStack/router PR #6897: improve github release changelog

The PR changes how GitHub release notes are generated:
- OLD: Parse git commits and group by conventional commit type (Feat, Fix, etc.)
- NEW: Read from package CHANGELOG.md files, only include bumped packages, add author attribution

Tests verify:
1. New functions exist (resolveAuthorForCommit, appendAuthors)
2. Script reads from CHANGELOG.md files for changelog content
3. Script only includes packages with version bumps
4. Author attribution is added to changelog entries
"""

import subprocess
import os
import re

REPO = "/workspace/router"
SCRIPT_PATH = os.path.join(REPO, "scripts", "create-github-release.mjs")


def read_script():
    """Read the release script content."""
    with open(SCRIPT_PATH, "r") as f:
        return f.read()


# ============================================================================
# FAIL-TO-PASS TESTS
# These must FAIL on base commit and PASS after the fix
# ============================================================================


def test_resolve_author_for_commit_function_exists():
    """
    The fix adds a new function `resolveAuthorForCommit` that maps commit
    hashes to author attribution strings.

    fail_to_pass: Function does not exist in base commit.
    """
    content = read_script()
    # Check for the function definition
    assert "async function resolveAuthorForCommit" in content, (
        "Expected resolveAuthorForCommit function to be defined. "
        "The new implementation should include a function that resolves "
        "commit hashes to author strings."
    )


def test_append_authors_function_exists():
    """
    The fix adds a new function `appendAuthors` that appends author info
    to changelog lines containing commit hashes.

    fail_to_pass: Function does not exist in base commit.
    """
    content = read_script()
    # Check for the function definition
    assert "async function appendAuthors" in content, (
        "Expected appendAuthors function to be defined. "
        "The new implementation should include a function that appends "
        "author attribution to changelog entries."
    )


def test_reads_changelog_files():
    """
    The fix changes the script to read from CHANGELOG.md files instead of
    parsing git commits directly.

    fail_to_pass: Base commit parses git log, not CHANGELOG.md files.
    """
    content = read_script()
    # Check that the script reads CHANGELOG.md files
    assert "CHANGELOG.md" in content, (
        "Expected script to reference CHANGELOG.md files. "
        "The new implementation reads changelog entries from package-specific "
        "CHANGELOG.md files generated by changesets."
    )
    # Should read the changelog file content (variable may be on different line)
    assert "changelogPath" in content and "readFileSync" in content, (
        "Expected script to read CHANGELOG.md file content using readFileSync. "
        "The changelogPath variable should hold the CHANGELOG.md path."
    )


def test_detects_bumped_packages():
    """
    The fix adds logic to detect which packages were actually bumped by
    comparing versions between releases.

    fail_to_pass: Base commit lists all packages, not just bumped ones.
    """
    content = read_script()
    # Check for bumped packages detection logic
    assert "bumpedPackages" in content, (
        "Expected bumpedPackages variable to track packages with version changes. "
        "The new implementation compares package versions between releases."
    )


def test_version_comparison_logic():
    """
    The fix compares current version with previous release version to
    determine which packages were actually bumped.

    fail_to_pass: Base commit doesn't compare versions.
    """
    content = read_script()
    # Check for version comparison
    assert re.search(r"prevPkg\.version\s*!==\s*currentPkg\.version", content), (
        "Expected version comparison between previous and current package versions. "
        "The script should compare prevPkg.version !== currentPkg.version."
    )


def test_extracts_version_section():
    """
    The fix extracts the changelog section for the specific version by
    finding the version header in the CHANGELOG.md file.

    fail_to_pass: Base commit doesn't parse CHANGELOG.md version sections.
    """
    content = read_script()
    # Check for version header extraction
    assert "versionHeader" in content or "## ${pkg.version}" in content, (
        "Expected version header parsing logic. "
        "The script should find and extract content under '## <version>' headers."
    )


def test_empty_changelog_message():
    """
    The fix changes the empty changelog fallback message from '- None'
    to '- No changelog entries'.

    fail_to_pass: Base commit uses '- None' message.
    """
    content = read_script()
    # Check for the new empty message
    assert "No changelog entries" in content, (
        "Expected '- No changelog entries' as the fallback message. "
        "The new implementation uses a more descriptive empty state message."
    )
    # Should NOT have the old message
    assert "'- None\\n\\n'" not in content and "- None\\n" not in content.replace("No changelog entries", ""), (
        "Should not use the old '- None' fallback message."
    )


def test_author_cache_variable():
    """
    The fix adds an authorCache to cache resolved authors by commit hash.

    fail_to_pass: Base commit doesn't have authorCache.
    """
    content = read_script()
    assert "authorCache" in content, (
        "Expected authorCache variable for caching author resolution results."
    )


def test_commit_hash_regex():
    """
    The fix includes a regex to match commit hash links in changelog entries
    like [`9a4d924`](url).

    fail_to_pass: Base commit doesn't parse changelog commit links.
    """
    content = read_script()
    # Check for the commit hash matching regex
    assert re.search(r"commitMatch", content), (
        "Expected commitMatch variable for matching commit hashes in changelog lines."
    )
    assert re.search(r"\[a-f0-9\]", content), (
        "Expected regex pattern for matching hexadecimal commit hashes."
    )


def test_package_header_format():
    """
    The fix formats changelog output with package-specific headers using
    '#### ${pkg.name}' format instead of '### Type' format.

    fail_to_pass: Base commit uses type-based headers (### Feat, ### Fix, etc.)
    """
    content = read_script()
    # Check for package-based headers
    assert re.search(r"####\s*\$\{pkg\.name\}", content), (
        "Expected package-based headers with '#### ${pkg.name}' format. "
        "The new implementation organizes changelog by package, not commit type."
    )


# ============================================================================
# PASS-TO-PASS TESTS
# These should pass on both base commit and after the fix
# ============================================================================


def test_script_is_valid_esm():
    """
    The script should be valid ESM JavaScript that Node.js can parse.

    pass_to_pass: Both versions should be syntactically valid.
    """
    result = subprocess.run(
        ["node", "--check", SCRIPT_PATH],
        capture_output=True,
        text=True,
        timeout=30,
        cwd=REPO
    )
    assert result.returncode == 0, (
        f"Script has syntax errors:\n{result.stderr}"
    )


def test_script_has_required_imports():
    """
    The script should import necessary modules (fs, path, execSync, etc.)

    pass_to_pass: Both versions need these imports.
    """
    content = read_script()
    required_imports = ["fs", "path", "execSync", "globSync"]
    for imp in required_imports:
        assert imp in content, f"Expected import of '{imp}' module."


def test_script_uses_gh_token():
    """
    The script should reference GH_TOKEN or GITHUB_TOKEN for API access.

    pass_to_pass: Both versions use GitHub token.
    """
    content = read_script()
    assert "GH_TOKEN" in content or "GITHUB_TOKEN" in content, (
        "Expected reference to GitHub token environment variable."
    )


def test_resolve_username_function_exists():
    """
    Both versions should have the resolveUsername helper function.

    pass_to_pass: Function exists in both versions.
    """
    content = read_script()
    assert "async function resolveUsername" in content, (
        "Expected resolveUsername function to be defined."
    )


def test_creates_github_release():
    """
    The script should create a GitHub release (the core purpose).

    pass_to_pass: Both versions create releases.
    """
    content = read_script()
    # Check for release creation logic
    assert "releases" in content.lower() or "gh release" in content.lower() or "api.github.com" in content, (
        "Expected GitHub release creation logic."
    )


def test_eslint_passes():
    """
    The script should pass ESLint checks.

    pass_to_pass: Both versions should be lint-clean.
    """
    result = subprocess.run(
        ["npx", "eslint", SCRIPT_PATH],
        capture_output=True,
        text=True,
        timeout=120,
        cwd=REPO
    )
    assert result.returncode == 0, (
        f"ESLint errors in script:\n{result.stdout[-1500:]}\n{result.stderr[-500:]}"
    )


def test_repo_prettier_format():
    """
    The script should pass Prettier format checks.

    pass_to_pass: Both versions should be properly formatted.
    """
    result = subprocess.run(
        ["npx", "prettier", "--check", SCRIPT_PATH],
        capture_output=True,
        text=True,
        timeout=120,
        cwd=REPO
    )
    assert result.returncode == 0, (
        f"Prettier format check failed:\n{result.stdout[-1500:]}\n{result.stderr[-500:]}"
    )
