version = "1.0"

[metadata]
author_name = "Alex Li"
author_email = "alex@example.com"
difficulty = "medium"
category = "bugfix"
tags = [ "react", "dom", "focus", "fragment-refs", "javascript",]
expert_time_estimate_min = 20.0
junior_time_estimate_min = 45.0
source_repo = "facebook/react"
source_pr = 36010
base_commit = "8f4150605449efe909822d8b20fe529d85851afe"
merge_commit = "c80a07509582daadf275f36ffe7a88c3b12e9db4"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 1800.0

[environment]
build_timeout_sec = 600.0
cpus = 2
memory_mb = 8192
storage_mb = 20480
allow_internet = true
