#!/usr/bin/env bash
set -euo pipefail

cd /workspace/stackrox

# Idempotency guard
if grep -qF "- generally: conventional commit format (e.g., `fix(ui): description`) OR JIRA f" "AGENTS.md"; then
  echo "Gold patch already applied."
  exit 0
fi

git apply --whitespace=nowarn <<'PATCH'
diff --git a/AGENTS.md b/AGENTS.md
@@ -31,6 +31,27 @@ following requirements:
   being made, etc
 - include a note that the code was partially generated by AI
 
+### Creating Pull Requests
+
+When creating pull requests, you must follow these requirements:
+
+- always create PRs as draft - use the `--draft` flag with `gh pr create`
+- this allows for review and additional changes before marking as ready for review
+- add the `ai-assisted` label to PRs created with AI assistance
+- PR title must follow the format enforced by `.github/workflows/check-pr-title.yaml`
+  - read the workflow file to understand exact requirements
+  - generally: conventional commit format (e.g., `fix(ui): description`) OR JIRA format (e.g., `ROX-123: description`)
+  - maximum 70 characters
+- PR description must follow the template (`.github/pull_request_template.md`)
+  - IMPORTANT: all sections, checkboxes, and structure must be preserved
+  - only remove: HTML comments (`<!-- -->`) and placeholder text (e.g., "change me!")
+  - do not remove: section headers, checkboxes, or any structural content
+  - fill in all required sections and check appropriate boxes
+  - be super brief and stick to facts
+  - use emojis only when necessary
+  - include: problem definition, considered alternatives, explain whys for chosen solution, if applicable.
+  - include benchmark results if applicable
+
 ## Common Development Commands
 
 ### Build Commands
PATCH

echo "Gold patch applied."
