#!/usr/bin/env bash
set -euo pipefail

cd /workspace/tea-tasting

# Idempotency guard
if grep -qF "- Exception: if the class has an explicit `__init__`, put the class documentatio" "AGENTS.md"; then
  echo "Gold patch already applied."
  exit 0
fi

git apply --whitespace=nowarn <<'PATCH'
diff --git a/AGENTS.md b/AGENTS.md
@@ -3,7 +3,7 @@
 ## Project structure
 
 - `docs/`: documentation (for Material for MkDocs).
-- `examples/`: examples as marimo notebooks, autogenerated from `docs/*.md` guides, excluded from linting and type checking; don't edit directly.
+- `examples/`: examples as marimo notebooks, auto-generated from `docs/*.md` guides, excluded from linting and type checking; don't edit directly.
 - `src/_internal`: docs tooling (marimo example generation, markdown extensions).
 - `src/tea_tasting/`: public package code:
     - `src/tea_tasting/metrics/`: built-in metrics and metrics base classes.
@@ -14,7 +14,7 @@
     - `src/tea_tasting/multiplicity.py`: multiple testing corrections.
     - `src/tea_tasting/utils.py`: parameters validation, results formatting and rendering, graceful division by zero.
     - `src/tea_tasting/version.py`: package version extracted from `src/tea_tasting/_version.txt`.
-- `tests/`: unit tests for pytest; replicates `src/tea_tasting/` structure.
+- `tests/`: unit tests for pytest; mirrors `src/tea_tasting/` structure.
 
 ## Code style
 
@@ -28,18 +28,20 @@
 - Imports must satisfy Ruff isort rules (sorted within sections; two blank lines after imports).
 - Type annotations are required for all modules including tests and internal tooling; keep type hints accurate and narrow.
 - Using `cast` is usually discouraged: prefer correct annotations; if needed, use suppression (`# pyright: ignore`) over `cast`.
-- If the class has an explicit `__init__`, put the class documentation in `__init__`'s docstring; otherwise use a class docstring.
+- All code in `src/tea_tasting/` should be covered by tests in `tests/`, and expected code coverage is 100%.
 - Prefer pure functions and deterministic numeric behavior.
 
 ## Docs style
 
-- When writing guides and docstrings follow the Microsoft Writing Style Guide and Google developer documentation style guide.
-- All classes and functions except tests and autogenerated examples must have Google-style docstrings.
+- When writing guides and docstrings, follow the Microsoft Writing Style Guide and Google developer documentation style guide.
+- All classes and functions except tests and auto-generated examples must have Google-style docstrings.
+- Exception: if the class has an explicit `__init__`, put the class documentation in `__init__`'s docstring (suppress rule `D101` when Ruff reports it); otherwise, use a class docstring.
 
 ## Code testing and checking
 
 - Tests and checks for code changes:
-    - Tests: `uv run pytest`
+    - Tests: `uv run coverage run -m pytest`
+    - Code coverage (after tests): `uv run coverage report -m`
     - Full doctest: `uv run pytest --doctest-continue-on-failure --doctest-glob=*.md --doctest-modules --ignore=examples/ --ignore=tests/ --ignore-glob=src/_*`
     - Linting: `uv run ruff check`
     - Type checking: `uv run pyright`
@@ -49,12 +51,12 @@
 ## Docs testing and checking
 
 - Tests and checks for docs changes:
-    - Docs-only doctest: `uv run pytest --doctest-continue-on-failure --doctest-glob=*.md`
+    - Docs-only doctest: `uv run pytest --doctest-continue-on-failure --doctest-glob=*.md --ignore=tests/`
     - Markdown lint: `markdownlint-cli2 "README.md" "docs/*.md"`
 - Run them after creating or updating markdown files; fix errors.
 
 ## Code versioning
 
 - Develop only in the `dev` branch, never merge into `main`; leave all merges to me.
 - Make atomic commits.
-- Follow conventional commits standard in commit messages.
+- Follow the Conventional Commits standard in commit messages.
PATCH

echo "Gold patch applied."
