#!/usr/bin/env bash
set -euo pipefail

cd /workspace/e-invoice-eu

# Idempotency guard
if grep -qF "The exact wording differs, but it is always clear that changes to the file will" ".agents/skills/repo-generated-files/SKILLS.md"; then
  echo "Gold patch already applied."
  exit 0
fi

git apply --whitespace=nowarn <<'PATCH'
diff --git a/.agents/skills/repo-generated-files/SKILLS.md b/.agents/skills/repo-generated-files/SKILLS.md
@@ -18,20 +18,32 @@ and similar directories.
 - **Generated files are read-only.**
   - Do not edit manually.
   - Edits must be made in the **source from which the file is generated**, e.g., mapping YAML, XSL files, or scripts.
-- **First line always contains a warning comment**, e.g.:
+- **First line always contains a warning comment!**. Example:
   
 ```ts
-// This file is generated. Do NOT edit! Edit <source file> instead.
+/**
+ * This file was automatically generated by json-schema-to-typescript.
+ * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
+ * and run json-schema-to-typescript to regenerate this file.
+ */
 
 // ... generated content follows.
 ```
 
+The exact wording differs, but it is always clear that changes to the file will
+be overwritten.
+
 Generated files include:
 
-* TypeScript interfaces (.ts) generated from JSON schemas
 * JSON schema definitions (.json)
+* TypeScript interfaces (.ts) generated from JSON schemas
 * Mapping scaffolds for spreadsheet → JSON → XML transformations
 
+The JSON schema files do not contain a comment that they are generated,
+because JSON does not allow comments. There are only to such files,
+`packages/core/src/schema/invoice.schema.json` and
+`packages/core/src/schema/mapping.schema.json`.
+
 ## Updating Generated Files
 Files are updated by scripts in `packages/core/scripts/` via
 `packages/core/Makefile`.
PATCH

echo "Gold patch applied."
