"""Behavioral checks for tsgolint-choreai-add-agentsmd-file (markdown_authoring task).

Each test asserts that a distinctive literal from the gold patch appears
in the target tier-1 file after the agent runs.
"""
from __future__ import annotations

from pathlib import Path

REPO = Path("/workspace/tsgolint")


def _read(path: str) -> str:
    p = REPO / path
    assert p.is_file(), f"{p} does not exist"
    return p.read_text(encoding="utf-8", errors="replace")


def test_signal_00():
    """Distinctive line from gold patch must be present."""
    text = _read('AGENTS.md')
    assert 'TSGolint is a static analysis tool, based on typescript-go, for implementing and running type aware linting rules on TypeScript code.' in text, "expected to find: " + 'TSGolint is a static analysis tool, based on typescript-go, for implementing and running type aware linting rules on TypeScript code.'[:80]


def test_signal_01():
    """Distinctive line from gold patch must be present."""
    text = _read('AGENTS.md')
    assert '5. The patches will be applied during the build process using `git am --3way --no-gpg-sign ../patches/*.patch`' in text, "expected to find: " + '5. The patches will be applied during the build process using `git am --3way --no-gpg-sign ../patches/*.patch`'[:80]


def test_signal_02():
    """Distinctive line from gold patch must be present."""
    text = _read('AGENTS.md')
    assert 'The code within `./shim` is generated, do not edit it. The code can be re-generated by running `just shim`.' in text, "expected to find: " + 'The code within `./shim` is generated, do not edit it. The code can be re-generated by running `just shim`.'[:80]

