"""Behavioral checks for saleor-added-claude-skills-some-rules (markdown_authoring task).

Each test asserts that a distinctive literal from the gold patch appears
in the target tier-1 file after the agent runs.
"""
from __future__ import annotations

from pathlib import Path

REPO = Path("/workspace/saleor")


def _read(path: str) -> str:
    p = REPO / path
    assert p.is_file(), f"{p} does not exist"
    return p.read_text(encoding="utf-8", errors="replace")


def test_signal_00():
    """Distinctive line from gold patch must be present."""
    text = _read('.claude/skills/saleor-django-migration/SKILL.md')
    assert 'description: Generate Django schema migrations for the Saleor codebase using manage.py makemigrations. Use when (1) a new Django model is created, (2) model fields are added/altered/removed, (3) user ' in text, "expected to find: " + 'description: Generate Django schema migrations for the Saleor codebase using manage.py makemigrations. Use when (1) a new Django model is created, (2) model fields are added/altered/removed, (3) user '[:80]


def test_signal_01():
    """Distinctive line from gold patch must be present."""
    text = _read('.claude/skills/saleor-django-migration/SKILL.md')
    assert 'If the migration alters MORE THAN ONE field within a single model (e.g. two `AddField` or two `AlterField` operations on the same model), split into separate migrations — one per field. Delete the com' in text, "expected to find: " + 'If the migration alters MORE THAN ONE field within a single model (e.g. two `AddField` or two `AlterField` operations on the same model), split into separate migrations — one per field. Delete the com'[:80]


def test_signal_02():
    """Distinctive line from gold patch must be present."""
    text = _read('.claude/skills/saleor-django-migration/SKILL.md')
    assert '- Rely on autogenerated migrations for correct timestamps, sequential numbers, dependencies, and field definitions. If you must hand-edit (e.g. to split), regenerate rather than edit — delete the migr' in text, "expected to find: " + '- Rely on autogenerated migrations for correct timestamps, sequential numbers, dependencies, and field definitions. If you must hand-edit (e.g. to split), regenerate rather than edit — delete the migr'[:80]


def test_signal_03():
    """Distinctive line from gold patch must be present."""
    text = _read('saleor/graphql/AGENTS.md')
    assert '**Register query cost multipliers for limited/paginated fields.** When adding a new field with a `limit` argument, update `saleor/graphql/query_cost_map.py` so the `limit` value is used as a cost mult' in text, "expected to find: " + '**Register query cost multipliers for limited/paginated fields.** When adding a new field with a `limit` argument, update `saleor/graphql/query_cost_map.py` so the `limit` value is used as a cost mult'[:80]


def test_signal_04():
    """Distinctive line from gold patch must be present."""
    text = _read('saleor/graphql/AGENTS.md')
    assert "**Return the created or mutated object from mutations.** Callers may need the created object's ID or fields immediately after the mutation. Always include the result object in the mutation response ty" in text, "expected to find: " + "**Return the created or mutated object from mutations.** Callers may need the created object's ID or fields immediately after the mutation. Always include the result object in the mutation response ty"[:80]


def test_signal_05():
    """Distinctive line from gold patch must be present."""
    text = _read('saleor/graphql/AGENTS.md')
    assert '**Use `Meta.permissions` rather than manual permission checks in `perform_mutation`.** The `BaseMutation.mutate` method already calls `check_permissions` using the permissions declared in `Meta`.' in text, "expected to find: " + '**Use `Meta.permissions` rather than manual permission checks in `perform_mutation`.** The `BaseMutation.mutate` method already calls `check_permissions` using the permissions declared in `Meta`.'[:80]


def test_signal_06():
    """Distinctive line from gold patch must be present."""
    text = _read('saleor/graphql/CLAUDE.md')
    assert 'saleor/graphql/CLAUDE.md' in text, "expected to find: " + 'saleor/graphql/CLAUDE.md'[:80]

