"""Behavioral checks for tea-tasting-chore-add-agentsmd (markdown_authoring task).

Each test asserts that a distinctive literal from the gold patch appears
in the target tier-1 file after the agent runs.
"""
from __future__ import annotations

from pathlib import Path

REPO = Path("/workspace/tea-tasting")


def _read(path: str) -> str:
    p = REPO / path
    assert p.is_file(), f"{p} does not exist"
    return p.read_text(encoding="utf-8", errors="replace")


def test_signal_00():
    """Distinctive line from gold patch must be present."""
    text = _read('AGENTS.md')
    assert '- Full doctest: `uv run pytest --doctest-continue-on-failure --doctest-glob=*.md --doctest-modules --ignore=examples/ --ignore=tests/ --ignore-glob=src/_*`' in text, "expected to find: " + '- Full doctest: `uv run pytest --doctest-continue-on-failure --doctest-glob=*.md --doctest-modules --ignore=examples/ --ignore=tests/ --ignore-glob=src/_*`'[:80]


def test_signal_01():
    """Distinctive line from gold patch must be present."""
    text = _read('AGENTS.md')
    assert "- `examples/`: examples as marimo notebooks, autogenerated from `docs/*.md` guides, excluded from linting and type checking; don't edit directly." in text, "expected to find: " + "- `examples/`: examples as marimo notebooks, autogenerated from `docs/*.md` guides, excluded from linting and type checking; don't edit directly."[:80]


def test_signal_02():
    """Distinctive line from gold patch must be present."""
    text = _read('AGENTS.md')
    assert '- `src/tea_tasting/aggr.py`: aggregated statistics helpers (count/mean/var/cov), Delta method for variance and covariance of ratio metrics.' in text, "expected to find: " + '- `src/tea_tasting/aggr.py`: aggregated statistics helpers (count/mean/var/cov), Delta method for variance and covariance of ratio metrics.'[:80]

