"""Behavioral checks for sqlserver.rules-update-copilot-instructions-to-never (markdown_authoring task).

Each test asserts that a distinctive literal from the gold patch appears
in the target tier-1 file after the agent runs.
"""
from __future__ import annotations

from pathlib import Path

REPO = Path("/workspace/sqlserver.rules")


def _read(path: str) -> str:
    p = REPO / path
    assert p.is_file(), f"{p} does not exist"
    return p.read_text(encoding="utf-8", errors="replace")


def test_signal_00():
    """Distinctive line from gold patch must be present."""
    text = _read('.github/copilot-instructions.md')
    assert '**IMPORTANT**: Never make changes to any files in the `docs/` folder. This documentation is automatically generated by the `DocsGenerator` test class and should not be manually modified.' in text, "expected to find: " + '**IMPORTANT**: Never make changes to any files in the `docs/` folder. This documentation is automatically generated by the `DocsGenerator` test class and should not be manually modified.'[:80]

