#!/usr/bin/env bash
set -euo pipefail

cd /workspace/Ghost

# Idempotent: skip if already applied
if grep -q "migrate:create" ghost/core/package.json 2>/dev/null; then
    echo "Patch already applied."
    exit 0
fi

# Install semver if not present
if [ ! -d ghost/core/node_modules/semver ]; then
    echo "Installing semver..."
    (cd ghost/core && npm install --no-save semver 2>/dev/null || true)
fi

# Also link npm's built-in semver as fallback
if [ -d /usr/local/lib/node_modules/npm/node_modules/semver ] && [ ! -e ghost/core/node_modules/semver ]; then
    mkdir -p ghost/core/node_modules
    ln -sf /usr/local/lib/node_modules/npm/node_modules/semver ghost/core/node_modules/semver
fi

# Create the bin directory if needed
mkdir -p ghost/core/bin

# Create create-migration.js from base64
cat << 'B64END' | base64 -d > ghost/core/bin/create-migration.js
IyEvdXNyL2Jpbi9lbnYgbm9kZQovKiBlc2xpbnQtZGlzYWJsZSBuby1jb25zb2xlLCBnaG9zdC9naG9zdC1jdXN0b20vbm8tbmF0aXZlLWVycm9yICovCgpjb25zdCBwYXRoID0gcmVxdWlyZSgicGF0aCIpOwpjb25zdCBmcyA9IHJlcXVpcmUoImZzIik7CmNvbnN0IHNlbXZlciA9IHJlcXVpcmUoInNlbXZlciIpOwoKY29uc3QgTUlHUkFUSU9OX1RFTVBMQVRFID0gYGNvbnN0IGxvZ2dpbmcgPSByZXF1aXJlKCJAdHJ5Z2hvc3QvbG9nZ2luZyIpOwoKLy8gRm9yIERETCAtIHNjaGVtYSBjaGFuZ2VzCi8vIGNvbnN0IHtjcmVhdGVOb25UcmFuc2FjdGlvbmFsTWlncmF0aW9ufSA9IHJlcXVpcmUoIi4uLy4uL3V0aWxzIik7CgovLyBGb3IgRE1MIC0gZGF0YSBjaGFuZ2VzCi8vIGNvbnN0IHtjcmVhdGVUcmFuc2FjdGlvbmFsTWlncmF0aW9ufSA9IHJlcXVpcmUoIi4uLy4uL3V0aWxzIik7CgovLyBPciB1c2UgYSBzcGVjaWZpYyBoZWxwZXIKLy8gY29uc3Qge2FkZFRhYmxlLCBjcmVhdGVBZGRDb2x1bW5NaWdyYXRpb259ID0gcmVxdWlyZSgiLi4vLi4vdXRpbHMiKTsKCm1vZHVsZS5leHBvcnRzID0gLyoqLzsKYDsKCmNvbnN0IFNMVUdfUEFUVEVSTiA9IC9eW2EtejAtOV0rKC1bYS16MC05XSspKiQvOwoKLyoqCiAqIFZhbGlkYXRlcyB0aGF0IGEgc2x1ZyBpcyBrZWJhYi1jYXNlIChsb3dlcmNhc2UgYWxwaGFudW1lcmljIHdpdGggc2luZ2xlIGh5cGhlbnMpLgogKi8KZnVuY3Rpb24gaXNWYWxpZFNsdWcoc2x1ZykgewogIHJldHVybiB0eXBlb2Ygc2x1ZyA9PT0gInN0cmluZyIgJiYgU0xVR19QQVRURVJOLnRlc3Qoc2x1Zyk7Cn0KCi8qKgogKiBSZXR1cm5zIHRoZSBtaWdyYXRpb24gdmVyc2lvbiBmb2xkZXIgbmFtZSBmb3IgdGhlIGdpdmVuIHBhY2thZ2UgdmVyc2lvbi4KICoKICogc2VtdmVyLmluYyh2LCAnbWlub3InKSBoYW5kbGVzIGJvdGggY2FzZXM6CiAqICAgLSBTdGFibGUgNi4xOC4wIOKGkiA2LjE5LjAgKGluY3JlbWVudHMgbWlub3IpCiAqICAgLSBQcmVyZWxlYXNlIDYuMTkuMC1yYy4wIOKGkiA2LjE5LjAgKHN0cmlwcyBwcmVyZWxlYXNlLCBrZWVwcyBtaW5vcikKICoKICogS2V5IGludmFyaWFudDogNi4xOC4wIGFuZCA2LjE5LjAtcmMuMCBib3RoIHByb2R1Y2UgZm9sZGVyICI2LjE5Ii4KICovCmZ1bmN0aW9uIGdldE5leHRNaWdyYXRpb25WZXJzaW9uKHZlcnNpb24pIHsKICBjb25zdCBuZXh0ID0gc2VtdmVyLmluYyh2ZXJzaW9uLCAibWlub3IiKTsKICBpZiAoIW5leHQpIHsKICAgIHRocm93IG5ldyBFcnJvcihgSW52YWxpZCB2ZXJzaW9uOiAke3ZlcnNpb259YCk7CiAgfQogIHJldHVybiBgJHtzZW12ZXIubWFqb3IobmV4dCl9LiR7c2VtdmVyLm1pbm9yKG5leHQpfWA7Cn0KCi8qKgogKiBDcmVhdGVzIGEgbWlncmF0aW9uIGZpbGUgYW5kIG9wdGlvbmFsbHkgYnVtcHMgcGFja2FnZSB2ZXJzaW9ucyB0byBSQy4KICoKICogQHBhcmFtIHtvYmplY3R9IG9wdGlvbnMKICogQHBhcmFtIHtzdHJpbmd9IG9wdGlvbnMuc2x1ZyAtIFRoZSBtaWdyYXRpb24gbmFtZSBpbiBrZWJhYi1jYXNlCiAqIEBwYXJhbSB7c3RyaW5nfSBvcHRpb25zLmNvcmVEaXIgLSBQYXRoIHRvIGdob3N0L2NvcmUgZGlyZWN0b3J5CiAqIEBwYXJhbSB7RGF0ZX0gICBbb3B0aW9ucy5kYXRlXSAtIE92ZXJyaWRlIHRoZSB0aW1lc3RhbXAgKGZvciB0ZXN0aW5nKQogKiBAcmV0dXJucyB7e21pZ3JhdGlvblBhdGg6IHN0cmluZywgcmNWZXJzaW9uOiBzdHJpbmd8bnVsbH19CiAqLwpmdW5jdGlvbiBjcmVhdGVNaWdyYXRpb24oeyBzbHVnLCBjb3JlRGlyLCBkYXRlIH0pIHsKICBpZiAoIWlzVmFsaWRTbHVnKHNsdWcpKSB7CiAgICB0aHJvdyBuZXcgRXJyb3IoCiAgICAgIGBJbnZhbGlkIHNsdWc6ICIke3NsdWd9Ii4gVXNlIGtlYmFiLWNhc2UgKGUuZy4gYWRkLWNvbHVtbi10by1wb3N0cylgCiAgICApOwogIH0KCiAgY29uc3QgbWlncmF0aW9uc0RpciA9IHBhdGguam9pbigKICAgIGNvcmVEaXIsCiAgICAiY29yZSIsCiAgICAic2VydmVyIiwKICAgICJkYXRhIiwKICAgICJtaWdyYXRpb25zIiwKICAgICJ2ZXJzaW9ucyIKICApOwogIGNvbnN0IGNvcmVQYWNrYWdlUGF0aCA9IHBhdGguam9pbihjb3JlRGlyLCAicGFja2FnZS5qc29uIik7CgogIGNvbnN0IGNvcmVQYWNrYWdlID0gSlNPTi5wYXJzZShmcy5yZWFkRmlsZVN5bmMoY29yZVBhY2thZ2VQYXRoLCAidXRmOCIpKTsKICBjb25zdCBjdXJyZW50VmVyc2lvbiA9IGNvcmVQYWNrYWdlLnZlcnNpb247CgogIGNvbnN0IG5leHRWZXJzaW9uID0gZ2V0TmV4dE1pZ3JhdGlvblZlcnNpb24oY3VycmVudFZlcnNpb24pOwogIGNvbnN0IHZlcnNpb25EaXIgPSBwYXRoLmpvaW4obWlncmF0aW9uc0RpciwgbmV4dFZlcnNpb24pOwoKICBjb25zdCB0aW1lc3RhbXAgPSAoZGF0ZSB8fCBuZXcgRGF0ZSgpKQogICAgLnRvSVNPU3RyaW5nKCkKICAgIC5zbGljZSgwLCAxOSkKICAgIC5yZXBsYWNlKCJUIiwgIi0iKQogICAgLnJlcGxhY2VBbGwoIjoiLCAiLSIpOwogIGNvbnN0IGZpbGVuYW1lID0gYCR7dGltZXN0YW1wfS0ke3NsdWd9LmpzYDsKICBjb25zdCBtaWdyYXRpb25QYXRoID0gcGF0aC5qb2luKHZlcnNpb25EaXIsIGZpbGVuYW1lKTsKCiAgZnMubWtkaXJTeW5jKHZlcnNpb25EaXIsIHsgcmVjdXJzaXZlOiB0cnVlIH0pOwogIHRyeSB7CiAgICBmcy53cml0ZUZpbGVTeW5jKG1pZ3JhdGlvblBhdGgsIE1JR1JBVElPTl9URU1QTEFURSwgeyBmbGFnOiAid3giIH0pOwogIH0gY2F0Y2ggKGVycikgewogICAgaWYgKGVyci5jb2RlID09PSAiRUVYSVNUIikgewogICAgICB0aHJvdyBuZXcgRXJyb3IoYE1pZ3JhdGlvbiBhbHJlYWR5IGV4aXN0czogJHttaWdyYXRpb25QYXRofWApOwogICAgfQogICAgdGhyb3cgZXJyOwogIH0KCiAgLy8gQXV0by1idW1wIHRvIFJDIGlmIHRoaXMgaXMgYSBzdGFibGUgdmVyc2lvbgogIGxldCByY1ZlcnNpb24gPSBudWxsOwogIGlmICghc2VtdmVyLnByZXJlbGVhc2UoY3VycmVudFZlcnNpb24pKSB7CiAgICByY1ZlcnNpb24gPSBzZW12ZXIuaW5jKGN1cnJlbnRWZXJzaW9uLCAicHJlbWlub3IiLCAicmMiKTsKCiAgICBjb3JlUGFja2FnZS52ZXJzaW9uID0gcmNWZXJzaW9uOwogICAgZnMud3JpdGVGaWxlU3luYygKICAgICAgY29yZVBhY2thZ2VQYXRoLAogICAgICBKU09OLnN0cmluZ2lmeShjb3JlUGFja2FnZSwgbnVsbCwgMikgKyAiXG4iCiAgICApOwoKICAgIGNvbnN0IGFkbWluUGFja2FnZVBhdGggPSBwYXRoLnJlc29sdmUoY29yZURpciwgIi4uIiwgImFkbWluIiwgInBhY2thZ2UuanNvbiIpOwogICAgaWYgKGZzLmV4aXN0c1N5bmMoYWRtaW5QYWNrYWdlUGF0aCkpIHsKICAgICAgY29uc3QgYWRtaW5QYWNrYWdlID0gSlNPTi5wYXJzZSgKICAgICAgICBmcy5yZWFkRmlsZVN5bmMoYWRtaW5QYWNrYWdlUGF0aCwgInV0ZjgiKQogICAgICApOwogICAgICBhZG1pblBhY2thZ2UudmVyc2lvbiA9IHJjVmVyc2lvbjsKICAgICAgZnMud3JpdGVGaWxlU3luYygKICAgICAgICBhZG1pblBhY2thZ2VQYXRoLAogICAgICAgIEpTT04uc3RyaW5naWZ5KGFkbWluUGFja2FnZSwgbnVsbCwgMikgKyAiXG4iCiAgICAgICk7CiAgICB9CiAgfQoKICByZXR1cm4geyBtaWdyYXRpb25QYXRoLCByY1ZlcnNpb24gfTsKfQoKLy8gQ0xJIGVudHJ5IHBvaW50CmlmIChyZXF1aXJlLm1haW4gPT09IG1vZHVsZSkgewogIGNvbnN0IHNsdWcgPSBwcm9jZXNzLmFyZ3ZbMl07CgogIGlmICghc2x1ZykgewogICAgY29uc29sZS5lcnJvcigiVXNhZ2U6IHlhcm4gbWlncmF0ZTpjcmVhdGUgPHNsdWc+Iik7CiAgICBjb25zb2xlLmVycm9yKCIgIHNsdWc6IGtlYmFiLWNhc2UgbWlncmF0aW9uIG5hbWUgKGUuZy4gYWRkLWNvbHVtbi10by1wb3N0cykiKTsKICAgIHByb2Nlc3MuZXhpdCgxKTsKICB9CgogIHRyeSB7CiAgICBjb25zdCBjb3JlRGlyID0gcGF0aC5yZXNvbHZlKF9fZGlybmFtZSwgIi4uIik7CiAgICBjb25zdCB7IG1pZ3JhdGlvblBhdGgsIHJjVmVyc2lvbiB9ID0gY3JlYXRlTWlncmF0aW9uKHsgc2x1ZywgY29yZURpciB9KTsKCiAgICBjb25zb2xlLmxvZyhgQ3JlYXRlZCBtaWdyYXRpb246ICR7bWlncmF0aW9uUGF0aH1gKTsKICAgIGlmIChyY1ZlcnNpb24pIHsKICAgICAgY29uc29sZS5sb2coYEJ1bXBlZCB2ZXJzaW9uIHRvICR7cmNWZXJzaW9ufWApOwogICAgfQogIH0gY2F0Y2ggKGVycikgewogICAgY29uc29sZS5lcnJvcihlcnIubWVzc2FnZSk7CiAgICBwcm9jZXNzLmV4aXQoMSk7CiAgfQp9Cgptb2R1bGUuZXhwb3J0cyA9IHsgaXNWYWxpZFNsdWcsIGdldE5leHRNaWdyYXRpb25WZXJzaW9uLCBjcmVhdGVNaWdyYXRpb24gfTsK
B64END

# Make it executable
chmod +x ghost/core/bin/create-migration.js

# Verify syntax
if ! node --check ghost/core/bin/create-migration.js 2>/dev/null; then
    echo "ERROR: Generated script has syntax errors"
    exit 1
fi

# Add migrate:create script to package.json
cat > /tmp/update_pkg.js << 'NODEEND'
const fs = require("fs");
const pkg = JSON.parse(fs.readFileSync("ghost/core/package.json", "utf8"));
if (!pkg.scripts["migrate:create"]) {
    pkg.scripts["migrate:create"] = "node bin/create-migration.js";
    fs.writeFileSync("ghost/core/package.json", JSON.stringify(pkg, null, 2) + "\n");
    console.log("Added migrate:create script");
}
NODEEND
node /tmp/update_pkg.js

echo "Patch applied successfully."
