#!/bin/bash
set -euo pipefail

cd /workspace/workers-sdk

git apply <<'PATCH'
diff --git a/fixtures/worker-with-resources/src/index.ts b/fixtures/worker-with-resources/src/index.ts
index a66d399bfd..562cf4c41a 100644
--- a/fixtures/worker-with-resources/src/index.ts
+++ b/fixtures/worker-with-resources/src/index.ts
@@ -1,4 +1,5 @@
-import { DurableObject } from "cloudflare:workers";
+import { DurableObject, WorkflowEntrypoint } from "cloudflare:workers";
+import type { WorkflowEvent, WorkflowStep } from "cloudflare:workers";

 export default {
 	async fetch(request: Request, env: Env): Promise<Response> {
@@ -70,6 +71,27 @@ export class MyDurableObject extends DurableObject<Env> {
 		return new Response("OK");
 	}
 }
+
+interface WorkflowParams {
+	name: string;
+}
+
+export class MyWorkflow extends WorkflowEntrypoint<Env, WorkflowParams> {
+	async run(event: WorkflowEvent<WorkflowParams>, step: WorkflowStep) {
+		const name = event.payload.name ?? "World";
+
+		const greeting = await step.do("greet", async () => `Hello, ${name}!`);
+
+		await step.sleep("wait", "1 second");
+
+		const result = await step.do("finalize", async () => {
+			return `${greeting} Workflow complete.`;
+		});
+
+		return result;
+	}
+}
+
 const SEED_DATA: [string, string][] = [
 	["greeting", "Hello, World!"],
 	["counter", "42"],
diff --git a/fixtures/worker-with-resources/worker-configuration.d.ts b/fixtures/worker-with-resources/worker-configuration.d.ts
index 1da4e06263..7a298c19d4 100644
--- a/fixtures/worker-with-resources/worker-configuration.d.ts
+++ b/fixtures/worker-with-resources/worker-configuration.d.ts
@@ -1,5 +1,5 @@
 /* eslint-disable */
-// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 9b4b1032686eb7f16ed05d3e59c53f88)
+// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 3080c55aa34f3cfa38c5e93fb9275475)
 declare namespace Cloudflare {
 	interface GlobalProps {
 		mainModule: typeof import("./src/index");
@@ -12,6 +12,9 @@ declare namespace Cloudflare {
 		DB: D1Database;
 		BACKUP_DB: D1Database;
 		DO: DurableObjectNamespace<import("./src/index").MyDurableObject>;
+		MY_WORKFLOW: Workflow<
+			Parameters<import("./src/index").MyWorkflow["run"]>[0]["payload"]
+		>;
 	}
 }
 interface Env extends Cloudflare.Env {}
diff --git a/fixtures/worker-with-resources/wrangler.jsonc b/fixtures/worker-with-resources/wrangler.jsonc
index 86ed1af080..995e3007c5 100644
--- a/fixtures/worker-with-resources/wrangler.jsonc
+++ b/fixtures/worker-with-resources/wrangler.jsonc
@@ -27,6 +27,13 @@
 			"database_id": "some-db-id",
 		},
 	],
+	"workflows": [
+		{
+			"binding": "MY_WORKFLOW",
+			"class_name": "MyWorkflow",
+			"name": "my-workflow",
+		},
+	],
 	"durable_objects": {
 		"bindings": [
 			{
PATCH

# Idempotency check
grep -q 'export class MyWorkflow extends WorkflowEntrypoint' fixtures/worker-with-resources/src/index.ts
