"""Behavioral checks for swift-winrt-add-agentsmd (markdown_authoring task).

Each test asserts that a distinctive literal from the gold patch appears
in the target tier-1 file after the agent runs.
"""
from __future__ import annotations

from pathlib import Path

REPO = Path("/workspace/swift-winrt")


def _read(path: str) -> str:
    p = REPO / path
    assert p.is_file(), f"{p} does not exist"
    return p.read_text(encoding="utf-8", errors="replace")


def test_signal_00():
    """Distinctive line from gold patch must be present."""
    text = _read('AGENTS.md')
    assert '- Tests are in the `tests` subfolder. There is a `test_app` subfolder which contains code for all the test cases and the executable which runs them. There is also a `test_component` folder, this house' in text, "expected to find: " + '- Tests are in the `tests` subfolder. There is a `test_app` subfolder which contains code for all the test cases and the executable which runs them. There is also a `test_component` folder, this house'[:80]


def test_signal_01():
    """Distinctive line from gold patch must be present."""
    text = _read('AGENTS.md')
    assert '- Code in the `tests/test_component/Sources` subfolder is generated by `swiftwinrt` as part of the build. These files should not be hand-edited. When you make changes to `swiftwinrt` and re-build, the' in text, "expected to find: " + '- Code in the `tests/test_component/Sources` subfolder is generated by `swiftwinrt` as part of the build. These files should not be hand-edited. When you make changes to `swiftwinrt` and re-build, the'[:80]


def test_signal_02():
    """Distinctive line from gold patch must be present."""
    text = _read('AGENTS.md')
    assert "- Tests use XCTest, but are run as part of an executable and don't use XCTest directly. Due to this, test cases have to be manually added to the list. Follow existing patterns to add new tests." in text, "expected to find: " + "- Tests use XCTest, but are run as part of an executable and don't use XCTest directly. Due to this, test cases have to be manually added to the list. Follow existing patterns to add new tests."[:80]

