#!/bin/bash
set -e

cd /workspace/kotlin

# Apply the gold patch for KT-85257 - Stop copying R8 output with AGP 9.1+
patch -p1 << 'PATCH'
diff --git a/libraries/tools/kotlin-compose-compiler/src/common/kotlin/org/jetbrains/kotlin/compose/compiler/gradle/internal/ComposeAgpMappingFile.kt b/libraries/tools/kotlin-compose-compiler/src/common/kotlin/org/jetbrains/kotlin/compose/compiler/gradle/internal/ComposeAgpMappingFile.kt
index e7c70b4aef7f9..5d229ce7877b6 100644
--- a/libraries/tools/kotlin-compose-compiler/src/common/kotlin/org/jetbrains/kotlin/compose/compiler/gradle/internal/ComposeAgpMappingFile.kt
+++ b/libraries/tools/kotlin-compose-compiler/src/common/kotlin/org/jetbrains/kotlin/compose/compiler/gradle/internal/ComposeAgpMappingFile.kt
@@ -28,6 +28,8 @@ import org.gradle.work.DisableCachingByDefault
 import org.gradle.workers.WorkAction
 import org.gradle.workers.WorkParameters
 import org.gradle.workers.WorkerExecutor
+import org.jetbrains.kotlin.gradle.InternalKotlinGradlePluginApi
+import org.jetbrains.kotlin.gradle.plugin.AndroidGradlePluginVersion
 import org.jetbrains.kotlin.gradle.plugin.getKotlinPluginVersion
 import java.io.File
 import java.security.MessageDigest
@@ -35,7 +37,6 @@ import java.util.Locale.getDefault
 import java.util.zip.ZipFile
 import javax.inject.Inject

-
 internal fun Project.configureComposeMappingFile(
     enabled: Property<Boolean>
 ) {
@@ -78,13 +79,22 @@ internal fun Project.configureComposeMappingFile(
                     ProduceMappingFileTask::projectDirectories
                 )

-            val mergeTaskProvider = tasks.register<MergeMappingFileTask>("merge${name}ComposeMapping") {
-                composeMapping.set(produceTask.map { it.outputFile.get() })
+            val mergeTaskName = "merge${name}ComposeMapping"
+            val agpCopiesR8Output =
+                @OptIn(InternalKotlinGradlePluginApi::class)
+                AndroidGradlePluginVersion.currentOrNull.let {
+                    it != null && it.major >= 9 && it.minor >= 1
+                }
+            val mergeTaskProvider = if (agpCopiesR8Output) {
+                tasks.register<MergeMappingFileTask>(mergeTaskName)
+            } else {
+                tasks.register<MergeMappingFileTask.WithR8Outputs>(mergeTaskName)
             }
+            mergeTaskProvider.configure { it.composeMapping.set(produceTask.map { it.outputFile.get() }) }

             variant.artifacts
                 .use(mergeTaskProvider)
-                .wiredWithFiles(MergeMappingFileTask::originalFile, MergeMappingFileTask::output)
+                .wiredWithFiles(MergeMappingFileTask::r8MappingFile, MergeMappingFileTask::output)
                 .toTransform(uncheckedCast(SingleArtifact.OBFUSCATION_MAPPING_FILE))
         }
     }
@@ -256,20 +266,11 @@ internal abstract class ReportMappingErrorsTask : DefaultTask() {


 @CacheableTask
-internal abstract class MergeMappingFileTask @Inject constructor(
-    objects: ObjectFactory,
-    providers: ProviderFactory
-) : DefaultTask() {
+internal abstract class MergeMappingFileTask : DefaultTask() {

     @get:InputFile
     @get:PathSensitive(PathSensitivity.RELATIVE)
-    abstract val originalFile: RegularFileProperty
-
-    @get:InputFiles
-    @get:PathSensitive(PathSensitivity.RELATIVE)
-    val r8Outputs: FileCollection = objects.fileCollection()
-        .from(originalFile.asFile.map { it.parentFile })
-        .asFileTree
+    abstract val r8MappingFile: RegularFileProperty

     @get:InputFile
     @get:PathSensitive(PathSensitivity.RELATIVE)
@@ -278,23 +279,16 @@ internal abstract class MergeMappingFileTask @Inject constructor(
     @get:OutputFile
     abstract val output: RegularFileProperty

-    @get:OutputDirectory
-    val outputDir: Provider<File> = providers.provider { output.get().asFile.parentFile }
-
     @TaskAction
-    fun taskAction() {
+    open fun taskAction() {
         /*
          * Read the proguard file generated by R8, calculate the new SHA-256 hash for the header, and append Compose mapping.
          */
         val newHeader = buildHeader()

-        val originalFile = originalFile.get().asFile
+        val originalFile = r8MappingFile.get().asFile

         val outputFile = output.get().asFile
-        val outputDir = outputDir.get()
-
-        outputDir.deleteRecursively()
-        outputDir.mkdirs()

         outputFile.bufferedWriter().use { writer ->
             writer.append(newHeader)
@@ -314,15 +308,10 @@ internal abstract class MergeMappingFileTask @Inject constructor(
                 writer.appendLine(it)
             }
         }
-
-        r8Outputs.forEach {
-            if (it == originalFile) return@forEach
-            it.copyTo(File(outputDir, it.name))
-        }
     }

     private fun buildHeader(): String {
-        val mapping = originalFile.get().asFile
+        val mapping = r8MappingFile.get().asFile

         val digest = MessageDigest.getInstance("SHA-256")

@@ -366,4 +355,37 @@ internal abstract class MergeMappingFileTask @Inject constructor(
         }
         return headerString.replace("<SHA-256>".toRegex(), sha256String)
     }
+
+    // Workaround for https://issuetracker.google.com/469745905 that is only required until AGP 9.1
+    // Before that, R8 output files are produced next to the R8 mapping file instead of the output folder.
+    @CacheableTask
+    abstract class WithR8Outputs @Inject constructor(
+        objects: ObjectFactory,
+        providers: ProviderFactory
+    ) : MergeMappingFileTask() {
+        @get:InputFiles
+        @get:PathSensitive(PathSensitivity.RELATIVE)
+        val r8Outputs: FileCollection = objects.fileCollection()
+            .from(r8MappingFile.asFile.map { it.parentFile })
+            .asFileTree
+
+        @get:OutputDirectory
+        val outputDir: Provider<File> = providers.provider { output.get().asFile.parentFile }
+
+        @TaskAction
+        override fun taskAction() {
+            val originalFile = r8MappingFile.get().asFile
+            val outputDir = outputDir.get()
+
+            outputDir.deleteRecursively()
+            outputDir.mkdirs()
+
+            super.taskAction()
+
+            r8Outputs.forEach {
+                if (it == originalFile) return@forEach
+                it.copyTo(File(outputDir, it.name))
+            }
+        }
+    }
 }
\ No newline at end of file
PATCH

echo "Patch applied successfully"
