"""Pytest harness for pulumi/pulumi#22433.

The bug: `ProgressDisplay.handleSystemEvent` in pkg/backend/display/progress.go
holds the write lock on `eventMutex` while invoking `renderer.systemMessage`,
which (in the messageRenderer) calls back into code that acquires the read
lock — deadlocking on Ctrl+C in non-raw terminals.

The fail-to-pass test injects a system event into `ShowProgressEvents` running
with a non-raw mock terminal (the messageRenderer path) and waits for the done
channel. On the buggy base commit the renderer deadlocks; on the fixed code
the channel closes promptly.
"""
from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

import pytest

REPO = Path("/workspace/pulumi")
PKG = REPO / "pkg"
DISPLAY_DIR = PKG / "backend" / "display"
HARNESS_TEST_PATH = DISPLAY_DIR / "harness_pr22433_test.go"

# Distinctive function name keeps us out of any collision with a regression
# test the agent (or the gold patch) may add to progress_test.go.
HARNESS_TEST_GO = r'''// Copyright 2026, Task Harness.
//
// Regression harness for https://github.com/pulumi/pulumi/issues/21697.
// This file is generated by the test harness — do not edit.

package display

import (
	"bytes"
	"testing"
	"time"

	"github.com/pulumi/pulumi/pkg/v3/backend/display/internal/terminal"
	"github.com/pulumi/pulumi/pkg/v3/engine"
	"github.com/pulumi/pulumi/sdk/v3/go/common/diag/colors"
	"github.com/pulumi/pulumi/sdk/v3/go/common/tokens"
)

// TestHarnessSystemEventDoesNotDeadlock_PR22433 verifies that delivering a
// SystemEvent to the messageRenderer (raw=false mock terminal) does not
// deadlock — i.e. handleSystemEvent must release the write lock before
// invoking renderer.systemMessage.
func TestHarnessSystemEventDoesNotDeadlock_PR22433(t *testing.T) {
	t.Parallel()

	eventChannel, doneChannel := make(chan engine.Event), make(chan bool)

	var stdout bytes.Buffer

	go ShowProgressEvents(
		"test", "update", tokens.MustParseStackName("stack"), "project", "link", eventChannel, doneChannel,
		Options{
			IsInteractive:       true,
			Color:               colors.Raw,
			Stdout:              &stdout,
			Stderr:              &bytes.Buffer{},
			term:                terminal.NewMockTerminal(&stdout, 80, 24, false /* raw */),
			DeterministicOutput: true,
		}, false)

	go func() {
		eventChannel <- engine.NewEvent(engine.StdoutEventPayload{
			Message: "^C received; cancelling.\n",
			Color:   colors.Always,
		})
		eventChannel <- engine.NewCancelEvent()
		close(eventChannel)
	}()

	select {
	case <-doneChannel:
		// success
	case <-time.After(15 * time.Second):
		t.Fatal("display deadlocked processing system event with messageRenderer")
	}
}
'''


def _write_harness_test() -> None:
    HARNESS_TEST_PATH.write_text(HARNESS_TEST_GO)


def _remove_harness_test() -> None:
    try:
        HARNESS_TEST_PATH.unlink()
    except FileNotFoundError:
        pass


@pytest.fixture(scope="module", autouse=True)
def _harness_test_file():
    _write_harness_test()
    yield
    _remove_harness_test()


def _run_go_test(run_pattern: str, timeout_sec: int, extra_args: list[str] | None = None) -> subprocess.CompletedProcess:
    cmd = [
        "go", "test",
        "-count=1",
        "-timeout", f"{timeout_sec}s",
        "-run", run_pattern,
        "./backend/display/...",
    ]
    if extra_args:
        cmd.extend(extra_args)
    return subprocess.run(
        cmd,
        cwd=str(PKG),
        capture_output=True,
        text=True,
        timeout=timeout_sec + 30,
    )


def test_compiles():
    """Repo's pkg/backend/display package compiles. Pre-flight; if this
    fails every other test is meaningless."""
    r = subprocess.run(
        ["go", "build", "./backend/display/..."],
        cwd=str(PKG),
        capture_output=True,
        text=True,
        timeout=300,
    )
    assert r.returncode == 0, f"go build failed:\n{r.stderr[-2000:]}"


def test_system_event_does_not_deadlock_messagerenderer():
    """Fail-to-pass: sending a SystemEvent to the messageRenderer must not
    deadlock. On the buggy base commit, handleSystemEvent holds the write
    lock while the messageRenderer's systemMessage indirectly takes the
    read lock — `go test` aborts via -timeout."""
    r = _run_go_test("^TestHarnessSystemEventDoesNotDeadlock_PR22433$", timeout_sec=60)
    assert r.returncode == 0, (
        "Harness regression test failed.\n"
        f"stdout (tail):\n{r.stdout[-2000:]}\n"
        f"stderr (tail):\n{r.stderr[-2000:]}"
    )
    # Sanity: ensure the test actually ran (not just "no tests to run").
    assert "TestHarnessSystemEventDoesNotDeadlock_PR22433" in r.stdout or "ok" in r.stdout, (
        f"Test does not appear to have run.\nstdout:\n{r.stdout}\nstderr:\n{r.stderr}"
    )


def test_existing_progress_tests_still_pass():
    """Pass-to-pass: the existing pkg/backend/display progress tests must
    keep passing — sanity check that the fix doesn't regress display."""
    # Run a representative subset of the existing display tests.  Use the
    # repo's own test names rather than the entire package to keep the
    # runtime predictable.
    r = _run_go_test(
        "^(TestProgressEvents|TestSimpleProgressEvents|TestRowsTreeNode|TestDiff)",
        timeout_sec=300,
    )
    assert r.returncode == 0, (
        "Existing display tests regressed.\n"
        f"stdout (tail):\n{r.stdout[-2000:]}\n"
        f"stderr (tail):\n{r.stderr[-2000:]}"
    )


def test_handle_system_event_releases_lock_before_renderer():
    """Behavioural check: deadlock-free behaviour confirmed by the f2p
    test above. This test additionally verifies via subprocess that the
    fixed `handleSystemEvent` does NOT use a single `defer
    eventMutex.Unlock()` that spans the renderer call.

    We don't pin a specific implementation: any rewrite that releases the
    write lock before invoking `display.renderer.systemMessage` satisfies
    the contract. We assert the negative pattern: a `defer
    display.eventMutex.Unlock()` on the very first lines of the function
    paired with a renderer call later in the same function is the broken
    shape."""
    progress = (DISPLAY_DIR / "progress.go").read_text()
    # Locate the function body.
    needle = "func (display *ProgressDisplay) handleSystemEvent("
    start = progress.find(needle)
    assert start != -1, "handleSystemEvent function not found in progress.go"
    # Body ends at the next top-level `\n}\n` after start.
    end = progress.find("\n}\n", start)
    assert end != -1, "Could not locate end of handleSystemEvent body"
    body = progress[start:end]

    assert "display.renderer.systemMessage(payload)" in body, (
        "handleSystemEvent no longer calls renderer.systemMessage — "
        "implementation has diverged from the expected contract."
    )

    # The buggy shape: write-lock then defer-unlock at the top, then call
    # renderer.systemMessage later — meaning the unlock happens AFTER the
    # renderer call. The fix releases the lock before the renderer call.
    lock_idx = body.find("display.eventMutex.Lock()")
    defer_unlock_idx = body.find("defer display.eventMutex.Unlock()")
    renderer_idx = body.find("display.renderer.systemMessage(payload)")
    assert lock_idx != -1, "expected eventMutex.Lock() in handleSystemEvent"
    assert renderer_idx != -1
    if defer_unlock_idx != -1:
        # If a defer-unlock exists, it must be AFTER the renderer call (e.g.
        # guarding a smaller critical section that doesn't include the
        # renderer call).  A defer-unlock placed before the renderer call
        # is the buggy shape.
        assert defer_unlock_idx > renderer_idx, (
            "handleSystemEvent still defers eventMutex.Unlock() before "
            "calling renderer.systemMessage — the lock is held across the "
            "renderer call, which can deadlock."
        )
