#!/usr/bin/env bash
set -euo pipefail

cd /workspace/mlflow

# Idempotent: skip if already applied
if grep -q '_DELETED_DIFF_MESSAGE' .claude/skills/src/skills/commands/fetch_diff.py 2>/dev/null; then
    echo "Patch already applied."
    exit 0
fi

git apply - <<'PATCH'
diff --git a/.claude/skills/fetch-diff/SKILL.md b/.claude/skills/fetch-diff/SKILL.md
index 28f6cbd1ddb7e..ac5a5c1e9bbcd 100644
--- a/.claude/skills/fetch-diff/SKILL.md
+++ b/.claude/skills/fetch-diff/SKILL.md
@@ -62,6 +62,16 @@ index abc123..def456 100644
 [Auto-generated file - diff masked]
 ```

+**Deleted file (masked):**
+
+```
+diff --git a/path/to/removed.py b/dev/null
+index abc123..0000000 100644
+--- a/path/to/removed.py
++++ /dev/null
+[Deleted file - diff masked]
+```
+
 Each line is annotated as `old_line new_line | <marker> content`:

 - `-` marker (left number only) -> deleted line, `side=LEFT`, `line=old_line`
diff --git a/.claude/skills/src/skills/commands/fetch_diff.py b/.claude/skills/src/skills/commands/fetch_diff.py
index 744872414b020..0b073e276180a 100644
--- a/.claude/skills/src/skills/commands/fetch_diff.py
+++ b/.claude/skills/src/skills/commands/fetch_diff.py
@@ -13,6 +13,7 @@
 from skills.github import GitHubClient, parse_pr_url

 _MASKED_DIFF_MESSAGE = "[Auto-generated file - diff masked]"
+_DELETED_DIFF_MESSAGE = "[Deleted file - diff masked]"


 def extract_stacked_pr_base_sha(pr_body: str | None, head_ref: str) -> str | None:
@@ -67,32 +68,41 @@ def filter_diff(full_diff: str, file_patterns: list[str] | None = None) -> str:
     filtered_diff: list[str] = []
     in_included_file = False
     is_masked = False
+    is_deleted = False

     for line in lines:
         if line.startswith("diff --git"):
             if match := re.match(r"diff --git a/(.*?) b/(.*?)$", line):
                 file_path = match.group(2)
-                if file_path == "dev/null" or (
-                    file_patterns
-                    and not any(fnmatch.fnmatch(file_path, pat) for pat in file_patterns)
+
+                if file_patterns and not any(
+                    fnmatch.fnmatch(file_path, pat) for pat in file_patterns
                 ):
                     in_included_file = False
                     is_masked = False
+                    is_deleted = False
                 else:
                     in_included_file = True
+                    is_deleted = False
                     is_masked = is_autogenerated_file(file_path)
             else:
                 in_included_file = False
                 is_masked = False
+                is_deleted = False

             if in_included_file:
                 filtered_diff.append(line)
         elif in_included_file:
-            if is_masked:
+            if line.startswith("deleted file mode"):
+                is_deleted = True
+                is_masked = True
+                filtered_diff.append(line)
+            elif is_masked:
+                mask_message = _DELETED_DIFF_MESSAGE if is_deleted else _MASKED_DIFF_MESSAGE
                 if line.startswith("@@"):
                     # Only emit the mask message once (for the first hunk)
-                    if not filtered_diff or filtered_diff[-1] != _MASKED_DIFF_MESSAGE:
-                        filtered_diff.append(_MASKED_DIFF_MESSAGE)
+                    if not filtered_diff or filtered_diff[-1] != mask_message:
+                        filtered_diff.append(mask_message)
                 elif line.startswith(("--- ", "+++ ")):
                     # Preserve diff file headers for masked files.
                     filtered_diff.append(line)
@@ -107,18 +117,21 @@ def filter_diff(full_diff: str, file_patterns: list[str] | None = None) -> str:
     result_lines: list[str] = []
     old_line = 0
     new_line = 0
+    in_header = False

     for line in filtered_diff:
-        if line.startswith("@@"):
+        if line.startswith("diff --git"):
+            in_header = True
+            if result_lines:
+                result_lines.append("")
+            result_lines.append(line)
+        elif line.startswith("@@"):
+            in_header = False
             if match := re.match(r"@@ -(\d+)(?:,\d+)? \+(\d+)(?:,\d+)? @@", line):
                 old_line = int(match.group(1))
                 new_line = int(match.group(2))
             result_lines.append(line)
-        elif line.startswith("diff --git"):
-            if result_lines:
-                result_lines.append("")
-            result_lines.append(line)
-        elif line.startswith(("index ", "---", "+++")) or line == _MASKED_DIFF_MESSAGE:
+        elif in_header or line in (_MASKED_DIFF_MESSAGE, _DELETED_DIFF_MESSAGE):
             result_lines.append(line)
         elif line.startswith("-"):
             result_lines.append(f"{old_line:5d}       | {line}")

PATCH

echo "Patch applied successfully."
