"""Behavioral checks for affiliate-skills-docs-update-claudemd-with-8 (markdown_authoring task).

Each test asserts that a distinctive literal from the gold patch appears
in the target tier-1 file after the agent runs.
"""
from __future__ import annotations

from pathlib import Path

REPO = Path("/workspace/affiliate-skills")


def _read(path: str) -> str:
    p = REPO / path
    assert p.is_file(), f"{p} does not exist"
    return p.read_text(encoding="utf-8", errors="replace")


def test_signal_00():
    """Distinctive line from gold patch must be present."""
    text = _read('CLAUDE.md')
    assert '32 AI-powered skills for affiliate marketers. Full funnel across 8 stages: Research, Content, Blog, Landing, Distribution, Analytics, Automation, Meta.' in text, "expected to find: " + '32 AI-powered skills for affiliate marketers. Full funnel across 8 stages: Research, Content, Blog, Landing, Distribution, Analytics, Automation, Meta.'[:80]


def test_signal_01():
    """Distinctive line from gold patch must be present."""
    text = _read('CLAUDE.md')
    assert '- `tools/dist/affiliate-check` — compiled binary (gitignored, build with `bun build --compile tools/src/cli.ts --outfile tools/dist/affiliate-check`)' in text, "expected to find: " + '- `tools/dist/affiliate-check` — compiled binary (gitignored, build with `bun build --compile tools/src/cli.ts --outfile tools/dist/affiliate-check`)'[:80]


def test_signal_02():
    """Distinctive line from gold patch must be present."""
    text = _read('CLAUDE.md')
    assert '- `registry.json` — machine-readable index of all skills (auto-generated by `scripts/generate-registry.js`)' in text, "expected to find: " + '- `registry.json` — machine-readable index of all skills (auto-generated by `scripts/generate-registry.js`)'[:80]

