#!/usr/bin/env bash
set -euo pipefail

cd /workspace/bmad-method

# Idempotency guard
if grep -qF "description: Audit BMAD source files for file-reference convention violations us" ".claude/skills/bmad-os-audit-file-refs/SKILL.md" && grep -qF ".claude/skills/bmad-os-audit-file-refs/prompts/instructions.md" ".claude/skills/bmad-os-audit-file-refs/prompts/instructions.md" && grep -qF "See `prompts/instructions.md` for full prompt structure, severity ratings, and s" ".claude/skills/bmad-os-review-pr/README.md" && grep -qF "description: Adversarial PR review tool (Raven's Verdict). Cynical deep review t" ".claude/skills/bmad-os-review-pr/SKILL.md" && grep -qF "## CRITICAL: Sandboxed Execution Rules" ".claude/skills/bmad-os-review-pr/prompts/instructions.md"; then
  echo "Gold patch already applied."
  exit 0
fi

git apply --whitespace=nowarn <<'PATCH'
diff --git a/.claude/skills/bmad-os-audit-file-refs/SKILL.md b/.claude/skills/bmad-os-audit-file-refs/SKILL.md
@@ -0,0 +1,7 @@
+---
+name: bmad-os-audit-file-refs
+description: Audit BMAD source files for file-reference convention violations using parallel Haiku subagents. Use when checking path references in workflow and task files.
+disable-model-invocation: true
+---
+
+Read `prompts/instructions.md` and execute.
diff --git a/.claude/skills/bmad-os-audit-file-refs/prompts/instructions.md b/.claude/skills/bmad-os-audit-file-refs/prompts/instructions.md

diff --git a/.claude/skills/bmad-os-review-pr/README.md b/.claude/skills/bmad-os-review-pr/README.md
@@ -6,9 +6,9 @@ Adversarial code review for GitHub PRs. Works with any LLM agent.
 
 ## How It Works
 
-Point your agent at `review-pr.md` and ask it to review a specific PR:
+Use `/bmad-os-review-pr` to review a specific PR:
 
-> "Read tools/maintainer/review-pr.md and apply it to PR #123"
+> "Use /bmad-os-review-pr to review PR #123"
 
 The tool will:
 
@@ -17,7 +17,7 @@ The tool will:
 3. Transform findings into professional tone
 4. Preview the review and ask before posting
 
-See `review-pr.md` for full prompt structure, severity ratings, and sandboxing rules.
+See `prompts/instructions.md` for full prompt structure, severity ratings, and sandboxing rules.
 
 ## When to Use
 
diff --git a/.claude/skills/bmad-os-review-pr/SKILL.md b/.claude/skills/bmad-os-review-pr/SKILL.md
@@ -0,0 +1,7 @@
+---
+name: bmad-os-review-pr
+description: Adversarial PR review tool (Raven's Verdict). Cynical deep review transformed into professional engineering findings. Use when asked to review a PR.
+disable-model-invocation: true
+---
+
+Read `prompts/instructions.md` and execute.
diff --git a/.claude/skills/bmad-os-review-pr/prompts/instructions.md b/.claude/skills/bmad-os-review-pr/prompts/instructions.md
@@ -2,8 +2,7 @@
 
 A cynical adversarial review, transformed into cold engineering professionalism.
 
-<orientation>
-CRITICAL: Sandboxed Execution Rules
+## CRITICAL: Sandboxed Execution Rules
 
 Before proceeding, you MUST verify:
 
@@ -14,9 +13,6 @@ Before proceeding, you MUST verify:
 
 **If no explicit PR number/URL was provided, STOP immediately and ask:**
 "What PR number or URL should I review?"
-</orientation>
-
-<preflight-checks>
 
 ## Preflight Checks
 
@@ -97,9 +93,7 @@ gh pr diff {PR_NUMBER} [--repo {REPO}] --name-only | grep -E '\.(png|jpg|jpeg|gi
 
 Store list of binary files to skip. Note them in final output.
 
-</preflight-checks>
-
-<adversarial-review>
+## Adversarial Review
 
 ### 1.1 Run Cynical Review
 
@@ -130,9 +124,7 @@ Likely tag:
 - Add `[likely]` to findings with high confidence, e.g. with direct evidence
 - Sort findings by severity (Critical → Moderate → Minor), not by confidence
 
-</adversarial-review>
-
-<tone-transformation>
+## Tone Transformation
 
 **Transform the cynical output into cold engineering professionalism.**
 
@@ -177,9 +169,8 @@ Output format after transformation:
 _Review generated by Raven's Verdict. LLM-produced analysis - findings may be incorrect or lack context. Verify before acting._
 ```
 
-</tone-transformation>
+## Post Review
 
-<post-review>
 ### 3.1 Preview
 
 Display the complete transformed review to the user.
@@ -231,12 +222,10 @@ Do NOT use heredocs or `echo` - Markdown code blocks will break shell parsing. U
 
 Keep the temp file and inform user of location.
 
-</post-review>
+## Notes
 
-<notes>
 - The "cynical asshole" phase is internal only - never posted
 - Tone transform MUST happen before any external output
 - When in doubt, ask the user - never assume
 - If you're unsure about severity, err toward higher severity
 - If you're unsure about confidence, be honest and use Medium or Low
-</notes>
PATCH

echo "Gold patch applied."
