#!/usr/bin/env bash
set -euo pipefail

cd /workspace/templates

# Idempotency guard
if grep -qF "**IMPORTANT:** AI tools **MUST NEVER** fabricate or hallucinate \"Online Editor t" "AGENTS.md"; then
  echo "Gold patch already applied."
  exit 0
fi

git apply --whitespace=nowarn <<'PATCH'
diff --git a/AGENTS.md b/AGENTS.md
@@ -30,7 +30,7 @@ go install github.com/Domain-Connect/dc-template-linter@latest
 Validate a template file with:
 
 ```bash
-dc-template-linter -loglevel error -tolerate info <template-file.json>
+dc-template-linter -loglevel error -tolerate info -logos <template-file.json>
 ```
 
 **All templates must pass linting without errors before being considered valid.**
@@ -53,6 +53,24 @@ Place template files in the root directory of the repository.
 
 For reference, example templates using the provider `exampleservice.domainconnect.org` are available in this repository. These templates demonstrate proper structure and can be used as a starting point when creating new templates.
 
+## Commit Message Format
+
+When committing template changes, use the following format for the subject line:
+
+- **New template:** `add <providerName>, <serviceName>` (e.g., `add Example Domain Connect Service, Stateless Hosting Primary`)
+- **Modified template:** `modify <providerName>, <serviceName>`
+- **Deleted template:** `delete <providerName>, <serviceName>`
+- **Multiple templates:** `<providerName>, <num> templates` (e.g., `Example Domain Connect Service, 3 templates`)
+
+### Commit Body
+
+The commit body should follow the structure defined in [`.github/pull_request_template.md`](.github/pull_request_template.md). When creating commit messages, AI tools may:
+
+- Assist with checking `[ ]` checkboxes from the PR template
+- Help verify template quality rules
+
+**IMPORTANT:** AI tools **MUST NEVER** fabricate or hallucinate "Online Editor test results" links. These must be generated by actually using the [Online Editor](https://domainconnect.paulonet.eu/dc/free/templateedit).
+
 ## Key Quality Rules
 
 When modifying or creating templates, ensure compliance with these critical rules:
PATCH

echo "Gold patch applied."
