"""
Tests for withastro/astro#16080:
queuedRendering breaks .html pages by escaping their raw HTML string output.

Uses Node.js as the test runner since the dist files are ESM .js modules
that Python cannot import directly.
"""
import subprocess
import os
import json

REPO = os.environ.get('REPO', '/workspace/astro')


def _node_eval(script: str, timeout: int = 60) -> tuple[int, str, str]:
    """Run Node.js code and return (returncode, stdout, stderr)."""
    r = subprocess.run(
        ['node', '--input-type=module', '--eval', script],
        cwd=REPO,
        capture_output=True,
        text=True,
        timeout=timeout,
        env={**os.environ, 'NO_COLOR': '1'},
    )
    return r.returncode, r.stdout, r.stderr


def test_render_page_preserves_html_in_queued_rendering():
    """
    Fail-to-pass: renderPage with queuedRendering must not escape HTML
    from .html page components (those with astro:html = true).

    On the buggy base commit, the raw <script> tag is HTML-escaped to
    &lt;script&gt; because the queue builder treats plain strings as text.
    The fix marks these strings as HTMLString to signal they are already safe.
    """
    code = """
import { renderPage } from '/workspace/astro/packages/astro/dist/runtime/server/render/page.js';
import { NodePool } from '/workspace/astro/packages/astro/dist/runtime/server/render/queue/pool.js';

// Simulate the component factory generated by vite-plugin-html for a .html file.
function htmlPageFactory(props) {
    return '<body>\\n  <script src="/assets/app.js"></script>\\n</body>';
}
htmlPageFactory['astro:html'] = true;
htmlPageFactory.moduleId = 'src/pages/admin/index.html';

const mockResult = {
    _metadata: {
        hasHydrationScript: false,
        rendererSpecificHydrationScripts: new Set(),
        hasRenderedHead: false,
        renderedScripts: new Set(),
        hasDirectives: new Set(),
        hasRenderedServerIslandRuntime: false,
        headInTree: false,
        extraHead: [],
        extraStyleHashes: [],
        extraScriptHashes: [],
        propagators: new Set(),
    },
    styles: new Set(),
    scripts: new Set(),
    links: new Set(),
    componentMetadata: new Map(),
    cancelled: false,
    compressHTML: false,
    partial: false,
    response: { status: 200, statusText: 'OK', headers: new Headers() },
    shouldInjectCspMetaTags: false,
    _experimentalQueuedRendering: {
        enabled: true,
        pool: new NodePool(1000),
    },
};

const response = await renderPage(mockResult, htmlPageFactory, {}, null, false);
const html = await response.text();

if (!html.includes('<script src="/assets/app.js"></script>')) {
    console.error('FAIL: Expected unescaped <script> tag in output, got:\\n' + html);
    process.exit(1);
}
if (html.includes('&lt;script')) {
    console.error('FAIL: Expected no HTML-escaped tags in output, got:\\n' + html);
    process.exit(1);
}
console.log('PASS: HTML preserved correctly');
process.exit(0);
"""
    returncode, stdout, stderr = _node_eval(code, timeout=60)
    assert returncode == 0, f"renderPage test failed:\nSTDOUT: {stdout}\nSTDERR: {stderr[-1000:]}"


def test_render_page_still_escapes_html_in_regular_components():
    """
    Pass-to-pass: renderPage with queuedRendering must still escape HTML
    in regular (non-.html) page components. Only .html pages with astro:html=true
    should bypass escaping. This ensures the fix for .html pages does not accidentally
    disable escaping for regular components.
    """
    code = """
import { renderPage } from '/workspace/astro/packages/astro/dist/runtime/server/render/page.js';
import { NodePool } from '/workspace/astro/packages/astro/dist/runtime/server/render/queue/pool.js';

// Regular component factory — no astro:html flag
function regularFactory(props) {
    return '<script>alert("xss")</script>';
}
regularFactory.moduleId = 'src/pages/regular.astro';

const mockResult = {
    _metadata: {
        hasHydrationScript: false,
        rendererSpecificHydrationScripts: new Set(),
        hasRenderedHead: false,
        renderedScripts: new Set(),
        hasDirectives: new Set(),
        hasRenderedServerIslandRuntime: false,
        headInTree: false,
        extraHead: [],
        extraStyleHashes: [],
        extraScriptHashes: [],
        propagators: new Set(),
    },
    styles: new Set(),
    scripts: new Set(),
    links: new Set(),
    componentMetadata: new Map(),
    cancelled: false,
    compressHTML: false,
    partial: false,
    response: { status: 200, statusText: 'OK', headers: new Headers() },
    shouldInjectCspMetaTags: false,
    _experimentalQueuedRendering: {
        enabled: true,
        pool: new NodePool(1000),
    },
};

const response = await renderPage(mockResult, regularFactory, {}, null, false);
const html = await response.text();

// Regular (non-.html) component output should be escaped
const hasUnescapedScript = html.includes('<script>alert');
const hasEscapedScript = html.includes('&lt;script&gt;') || html.includes('&lt;script&gt;');

if (hasUnescapedScript) {
    console.error('FAIL: Regular component should have escaped HTML, got:\\n' + html);
    process.exit(1);
}
if (!hasEscapedScript) {
    console.error('FAIL: Expected HTML-escaped output for regular component, got:\\n' + html);
    process.exit(1);
}
console.log('PASS: Regular component HTML escaped correctly');
process.exit(0);
"""
    returncode, stdout, stderr = _node_eval(code, timeout=60)
    assert returncode == 0, f"Regular component test failed:\nSTDOUT: {stdout}\nSTDERR: {stderr[-1000:]}"


def test_build_succeeds():
    """
    Pass-to-pass: The astro package must build successfully on the base commit.
    """
    r = subprocess.run(
        ['pnpm', 'run', 'build', '--filter=astro'],
        cwd=REPO,
        capture_output=True,
        text=True,
        timeout=300,
    )
    assert r.returncode == 0, f"Build failed:\n{r.stderr[-1000:]}"


def test_queue_rendering_unit_tests_pass():
    """
    Pass-to-pass: The queue-rendering unit tests pass on the base commit.
    """
    r = subprocess.run(
        ['pnpm', '-C', 'packages/astro', 'exec', 'astro-scripts', 'test',
         'test/units/render/queue-rendering.test.js'],
        cwd=REPO,
        capture_output=True,
        text=True,
        timeout=120,
    )
    assert r.returncode == 0, f"Queue rendering tests failed:\n{r.stderr[-1000:]}"


def test_knip():
    """
    Pass-to-pass: knip (unused code detection) passes on the base commit.
    """
    r = subprocess.run(
        ['pnpm', 'exec', 'knip'],
        cwd=REPO,
        capture_output=True,
        text=True,
        timeout=300,
    )
    assert r.returncode == 0, f"knip failed:\n{r.stderr[-1000:]}"


def test_eslint():
    """
    Pass-to-pass: ESLint passes on the base commit.
    """
    r = subprocess.run(
        ['pnpm', 'run', 'eslint:ci'],
        cwd=REPO,
        capture_output=True,
        text=True,
        timeout=300,
        env={**os.environ, 'FORCE_COLOR': '0'},
    )
    assert r.returncode == 0, f"ESLint failed:\n{r.stderr[-1000:]}"


def test_types():
    """
    Pass-to-pass: TypeScript type checking passes on the base commit.
    """
    r = subprocess.run(
        ['pnpm', '-C', 'packages/astro', 'run', 'test:types'],
        cwd=REPO,
        capture_output=True,
        text=True,
        timeout=120,
    )
    assert r.returncode == 0, f"TypeScript type check failed:\n{r.stderr[-1000:]}"


def test_queue_pool_unit_tests():
    """
    Pass-to-pass: The NodePool unit tests pass on the base commit.
    """
    r = subprocess.run(
        ['node', '--test', 'test/units/render/queue-pool.test.js'],
        cwd=f"{REPO}/packages/astro",
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert r.returncode == 0, f"Queue pool tests failed:\n{r.stderr[-500:]}"


def test_queue_batching_unit_tests():
    """
    Pass-to-pass: The queue-batching unit tests pass on the base commit.
    """
    r = subprocess.run(
        ['node', '--test', 'test/units/render/queue-batching.test.js'],
        cwd=f"{REPO}/packages/astro",
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert r.returncode == 0, f"Queue batching tests failed:\n{r.stderr[-500:]}"
