#!/usr/bin/env bash
set -euo pipefail

cd /workspace/mlflow

# Idempotent: skip if already applied
if grep -q '_MASKED_DIFF_MESSAGE' .claude/skills/src/skills/commands/fetch_diff.py 2>/dev/null; then
    echo "Patch already applied."
    exit 0
fi

git apply - <<'PATCH'
diff --git a/.claude/skills/fetch-diff/SKILL.md b/.claude/skills/fetch-diff/SKILL.md
index 2c19d9d58139d..28f6cbd1ddb7e 100644
--- a/.claude/skills/fetch-diff/SKILL.md
+++ b/.claude/skills/fetch-diff/SKILL.md
@@ -7,7 +7,7 @@ allowed-tools:

 # Fetch PR Diff

-Fetches a pull request diff, filters out auto-generated files, and adds line numbers for easier review comment placement.
+Fetches a pull request diff and adds line numbers for easier review comment placement. Auto-generated files are shown with masked diffs.

 ## Usage

@@ -35,6 +35,8 @@ Token is auto-detected from `GH_TOKEN` env var or `gh auth token`.

 ## Output Example

+**Regular file:**
+
 ```
 diff --git a/path/to/file.py b/path/to/file.py
 index abc123..def456 100644
@@ -50,6 +52,16 @@ index abc123..def456 100644
 15    16 |  def process_data(input_file: str) -> dict:
 ```

+**Auto-generated file (masked):**
+
+```
+diff --git a/uv.lock b/uv.lock
+index abc123..def456 100644
+--- a/uv.lock
++++ b/uv.lock
+[Auto-generated file - diff masked]
+```
+
 Each line is annotated as `old_line new_line | <marker> content`:

 - `-` marker (left number only) -> deleted line, `side=LEFT`, `line=old_line`
diff --git a/.claude/skills/src/skills/commands/fetch_diff.py b/.claude/skills/src/skills/commands/fetch_diff.py
index e3c485031347b..744872414b020 100644
--- a/.claude/skills/src/skills/commands/fetch_diff.py
+++ b/.claude/skills/src/skills/commands/fetch_diff.py
@@ -12,6 +12,8 @@

 from skills.github import GitHubClient, parse_pr_url

+_MASKED_DIFF_MESSAGE = "[Auto-generated file - diff masked]"
+

 def extract_stacked_pr_base_sha(pr_body: str | None, head_ref: str) -> str | None:
     """Extract the base SHA from the stacked PR incremental diff link.
@@ -40,8 +42,8 @@ def extract_stacked_pr_base_sha(pr_body: str | None, head_ref: str) -> str | Non
     return None


-def should_exclude_file(file_path: str) -> bool:
-    """Exclude auto-generated (protobuf, lock files) and large files (notebooks)."""
+def is_autogenerated_file(file_path: str) -> bool:
+    """Return True if the file is auto-generated (protobuf, lock files, generated Java)."""
     path = Path(file_path)

     if path.suffix in {".py", ".pyi"} and path.is_relative_to("mlflow/protos"):
@@ -56,17 +58,15 @@ def should_exclude_file(file_path: str) -> bool:
         if "Generated by the protocol buffer compiler" in first_line:
             return True

-    if path.suffix == ".ipynb":
-        return True
-
     return False


 def filter_diff(full_diff: str, file_patterns: list[str] | None = None) -> str:
-    """Filter out excluded files and add line numbers to diff."""
+    """Filter diff, mask auto-generated files, and add line numbers."""
     lines = full_diff.split("\n")
     filtered_diff: list[str] = []
     in_included_file = False
+    is_masked = False

     for line in lines:
         if line.startswith("diff --git"):
@@ -77,15 +77,31 @@ def filter_diff(full_diff: str, file_patterns: list[str] | None = None) -> str:
                     and not any(fnmatch.fnmatch(file_path, pat) for pat in file_patterns)
                 ):
                     in_included_file = False
+                    is_masked = False
                 else:
-                    in_included_file = not should_exclude_file(file_path)
+                    in_included_file = True
+                    is_masked = is_autogenerated_file(file_path)
             else:
                 in_included_file = False
+                is_masked = False

             if in_included_file:
                 filtered_diff.append(line)
         elif in_included_file:
-            filtered_diff.append(line)
+            if is_masked:
+                if line.startswith("@@"):
+                    # Only emit the mask message once (for the first hunk)
+                    if not filtered_diff or filtered_diff[-1] != _MASKED_DIFF_MESSAGE:
+                        filtered_diff.append(_MASKED_DIFF_MESSAGE)
+                elif line.startswith(("--- ", "+++ ")):
+                    # Preserve diff file headers for masked files.
+                    filtered_diff.append(line)
+                elif not line.startswith(("+", "-", " ", "\\")):
+                    # Other metadata lines (index, mode changes, rename info) pass through.
+                    filtered_diff.append(line)
+                # Skip hunk content lines
+            else:
+                filtered_diff.append(line)

     # Add line numbers
     result_lines: list[str] = []
@@ -102,7 +118,7 @@ def filter_diff(full_diff: str, file_patterns: list[str] | None = None) -> str:
             if result_lines:
                 result_lines.append("")
             result_lines.append(line)
-        elif line.startswith("index ") or line.startswith("---") or line.startswith("+++"):
+        elif line.startswith(("index ", "---", "+++")) or line == _MASKED_DIFF_MESSAGE:
             result_lines.append(line)
         elif line.startswith("-"):
             result_lines.append(f"{old_line:5d}       | {line}")

PATCH

echo "Patch applied successfully."
