#!/usr/bin/env bash
set -euo pipefail

cd /workspace/sqlserver.rules

# Idempotency guard
if grep -qF "**IMPORTANT**: Never make changes to any files in the `docs/` folder. This docum" ".github/copilot-instructions.md"; then
  echo "Gold patch already applied."
  exit 0
fi

git apply --whitespace=nowarn <<'PATCH'
diff --git a/.github/copilot-instructions.md b/.github/copilot-instructions.md
@@ -76,6 +76,8 @@ Always reference these instructions first and fallback to search or bash command
 - `Naming/` - Documentation for naming rules (SRN* series)
 - `CodeSmells/` - Documentation for code smell rules (SML* series)
 
+**IMPORTANT**: Never make changes to any files in the `docs/` folder. This documentation is automatically generated by the `DocsGenerator` test class and should not be manually modified.
+
 ## Common Tasks
 
 ### Creating New Analysis Rules
PATCH

echo "Gold patch applied."
