"""
Test outputs for langchain OpenAI file translator fix.

Tests verify that file blocks without filenames get a default "LC_AUTOGENERATED"
placeholder filename when converted to OpenAI format.
"""

import subprocess
import sys
import warnings
from typing import Any

# Path to the langchain repo
REPO = "/workspace/langchain"
CORE_LIB = f"{REPO}/libs/core"


def _import_translator() -> Any:
    """Import the translator function from the core library."""
    sys.path.insert(0, f"{CORE_LIB}")
    try:
        from langchain_core.messages.block_translators.openai import (
            convert_to_openai_data_block,
        )
        return convert_to_openai_data_block
    finally:
        # Don't remove from path, might need it again
        pass


def test_placeholder_filename_added() -> None:
    """
    FAIL-TO-PASS: File blocks without filename get LC_AUTOGENERATED placeholder.

    Before fix: file block has no "filename" key when not provided
    After fix: file block has "filename": "LC_AUTOGENERATED" when not provided
    """
    convert_to_openai_data_block = _import_translator()

    # File block without filename (the bug scenario)
    file_block = {
        "type": "file",
        "mime_type": "application/pdf",
        "base64": "Zm9vYmFy",  # "foobar" in base64
    }

    # Convert and check result
    with warnings.catch_warnings(record=True):
        warnings.simplefilter("always")
        result = convert_to_openai_data_block(file_block)

    # Verify the result structure
    assert result["type"] == "file", f"Expected type 'file', got {result['type']}"
    assert "file" in result, f"Expected 'file' key in result, got {result.keys()}"

    # THE KEY ASSERTION: filename should be the placeholder
    file_data = result["file"]
    assert (
        "filename" in file_data
    ), f"Expected 'filename' key in file data, got {file_data.keys()}"
    assert (
        file_data["filename"] == "LC_AUTOGENERATED"
    ), f"Expected filename 'LC_AUTOGENERATED', got '{file_data.get('filename')}'"


def test_placeholder_filename_various_mime_types() -> None:
    """
    FAIL-TO-PASS: Placeholder filename works for various mime types.

    Tests multiple file types to ensure the fix applies broadly.
    """
    convert_to_openai_data_block = _import_translator()

    test_cases = [
        ("application/pdf", "pdf_data"),
        ("image/png", "png_data"),
        ("image/jpeg", "jpeg_data"),
        ("text/plain", "text_data"),
    ]

    for mime_type, base64_data in test_cases:
        file_block = {
            "type": "file",
            "mime_type": mime_type,
            "base64": "Zm9vYmFy",
        }

        with warnings.catch_warnings(record=True):
            warnings.simplefilter("always")
            result = convert_to_openai_data_block(file_block)

        file_data = result["file"]
        assert (
            file_data.get("filename") == "LC_AUTOGENERATED"
        ), f"For {mime_type}: expected 'LC_AUTOGENERATED', got '{file_data.get('filename')}'"


def test_existing_filename_preserved() -> None:
    """
    PASS-TO-PASS: File blocks with existing filename are not modified.

    If a filename is already provided, it should be preserved.
    """
    convert_to_openai_data_block = _import_translator()

    file_block = {
        "type": "file",
        "mime_type": "application/pdf",
        "base64": "Zm9vYmFy",
        "filename": "my-document.pdf",
    }

    # No warning should be issued when filename is provided
    with warnings.catch_warnings(record=True) as w:
        warnings.simplefilter("always")
        result = convert_to_openai_data_block(file_block)
        # Should not have any warnings about filename
        filename_warnings = [x for x in w if "filename" in str(x.message)]
        assert (
            len(filename_warnings) == 0
        ), f"Unexpected warning when filename provided: {[str(x.message) for x in filename_warnings]}"

    # Existing filename should be preserved
    file_data = result["file"]
    assert (
        file_data["filename"] == "my-document.pdf"
    ), f"Expected filename 'my-document.pdf', got '{file_data.get('filename')}'"


def test_warning_includes_placeholder_info() -> None:
    """
    FAIL-TO-PASS: Warning message mentions the placeholder filename.

    After fix, the warning should tell users what placeholder is being used.
    """
    convert_to_openai_data_block = _import_translator()

    file_block = {
        "type": "file",
        "mime_type": "application/pdf",
        "base64": "Zm9vYmFy",
    }

    with warnings.catch_warnings(record=True) as w:
        warnings.simplefilter("always")
        convert_to_openai_data_block(file_block)

        # Find the warning about filename
        filename_warnings = [x for x in w if "filename" in str(x.message)]
        assert (
            len(filename_warnings) >= 1
        ), f"Expected warning about filename, got: {[str(x.message) for x in w]}"

        warning_msg = str(filename_warnings[0].message)
        assert (
            "LC_AUTOGENERATED" in warning_msg
        ), f"Warning should mention 'LC_AUTOGENERATED', got: {warning_msg}"


def test_ruff_linting() -> None:
    """
    PASS-TO-PASS: Code passes ruff linting.

    Verifies the code meets the repo's style requirements.
    """
    target_file = f"{CORE_LIB}/langchain_core/messages/block_translators/openai.py"

    result = subprocess.run(
        ["python", "-m", "ruff", "check", target_file],
        capture_output=True,
        text=True,
        timeout=60,
        cwd=REPO,
    )

    assert (
        result.returncode == 0
    ), f"Ruff linting failed:\n{result.stdout}\n{result.stderr}"


def test_repo_unit_tests_block_translators() -> None:
    """
    PASS-TO-PASS: Repo unit tests for block_translators pass.

    Runs the existing unit tests for the block_translators module
    to verify no regressions in the codebase.
    """
    result = subprocess.run(
        [
            "uv", "run", "--group", "test",
            "pytest", "tests/unit_tests/messages/block_translators/test_openai.py", "-v",
            "--disable-socket", "--allow-unix-socket",
        ],
        capture_output=True,
        text=True,
        timeout=300,
        cwd=CORE_LIB,
    )

    assert (
        result.returncode == 0
    ), f"Unit tests for block_translators failed:\n{result.stderr[-1000:]}"


def test_repo_unit_tests_messages() -> None:
    """
    PASS-TO-PASS: Repo unit tests for messages module pass.

    Runs the existing unit tests for the messages module
    to verify no regressions in message handling code.
    """
    result = subprocess.run(
        [
            "uv", "run", "--group", "test",
            "pytest", "tests/unit_tests/messages/", "-v",
            "--disable-socket", "--allow-unix-socket",
        ],
        capture_output=True,
        text=True,
        timeout=300,
        cwd=CORE_LIB,
    )

    assert (
        result.returncode == 0
    ), f"Unit tests for messages failed:\n{result.stderr[-1000:]}"


def test_repo_ruff_format() -> None:
    """
    PASS-TO-PASS: Code passes ruff format check.

    Verifies the code formatting meets the repo's style requirements.
    """
    result = subprocess.run(
        [
            "uv", "run", "--group", "lint",
            "ruff", "format", f"{CORE_LIB}/langchain_core", "--diff",
        ],
        capture_output=True,
        text=True,
        timeout=120,
        cwd=REPO,
    )

    assert (
        result.returncode == 0
    ), f"Ruff format check failed:\n{result.stdout}\n{result.stderr}"


def test_file_block_data_structure() -> None:
    """
    FAIL-TO-PASS: Complete file block structure is valid for OpenAI.

    Verifies that the entire output structure matches what OpenAI expects.
    """
    convert_to_openai_data_block = _import_translator()

    file_block = {
        "type": "file",
        "mime_type": "application/pdf",
        "base64": "Zm9vYmFy",
    }

    with warnings.catch_warnings(record=True):
        warnings.simplefilter("always")
        result = convert_to_openai_data_block(file_block)

    # Verify complete structure
    assert isinstance(result, dict), f"Result should be dict, got {type(result)}"
    assert result.get("type") == "file", f"Expected type 'file'"

    file_data = result.get("file", {})
    assert isinstance(file_data, dict), f"file data should be dict"

    # Should have file_data (base64 content)
    assert (
        "file_data" in file_data
    ), f"Expected 'file_data' in file data, got {file_data.keys()}"
    assert file_data["file_data"].startswith(
        "data:application/pdf;base64,"
    ), f"file_data should have data URI prefix"

    # Should now have filename (the fix)
    assert "filename" in file_data, f"Expected 'filename' in file data"
    assert file_data["filename"] == "LC_AUTOGENERATED"
