#!/usr/bin/env bash
set -euo pipefail

cd /workspace/agentsys

# Idempotency guard
if grep -qF "description: \"Use when user asks to \\\"discover tasks\\\", \\\"find next task\\\", or \\" "adapters/opencode/skills/discover-tasks/SKILL.md" && grep -qF "description: \"Use when user asks to \\\"deep review the code\\\", \\\"thorough code re" "adapters/opencode/skills/orchestrate-review/SKILL.md" && grep -qF "description: \"Use when user asks to \\\"validate delivery\\\", \\\"check readiness\\\", " "adapters/opencode/skills/validate-delivery/SKILL.md" && grep -qF "description: \"Use when user asks to \\\"discover tasks\\\", \\\"find next task\\\", or \\" "plugins/next-task/skills/discover-tasks/SKILL.md" && grep -qF "description: \"Use when user asks to \\\"deep review the code\\\", \\\"thorough code re" "plugins/next-task/skills/orchestrate-review/SKILL.md" && grep -qF "description: \"Use when user asks to \\\"validate delivery\\\", \\\"check readiness\\\", " "plugins/next-task/skills/validate-delivery/SKILL.md"; then
  echo "Gold patch already applied."
  exit 0
fi

git apply --whitespace=nowarn <<'PATCH'
diff --git a/adapters/opencode/skills/discover-tasks/SKILL.md b/adapters/opencode/skills/discover-tasks/SKILL.md
@@ -1,7 +1,7 @@
 <!-- AUTO-GENERATED by scripts/gen-adapters.js - DO NOT EDIT -->
 ---
 name: discover-tasks
-description: "Use when discovering and prioritizing tasks from configured sources. Handles GitHub, GitLab, local files, and custom sources."
+description: "Use when user asks to \"discover tasks\", \"find next task\", or \"prioritize issues\". Discovers and ranks tasks from GitHub, GitLab, local files, and custom sources."
 version: 5.0.0
 ---
 
diff --git a/adapters/opencode/skills/orchestrate-review/SKILL.md b/adapters/opencode/skills/orchestrate-review/SKILL.md
@@ -1,7 +1,7 @@
 <!-- AUTO-GENERATED by scripts/gen-adapters.js - DO NOT EDIT -->
 ---
 name: orchestrate-review
-description: "Use when user asks to \"deep review the code\", \"thorough code review\", \"multi-pass review\", or when orchestrating Phase 9 review loop. Provides review pass definitions (code quality, security, performance, test coverage, specialists), signal detection patterns, and iteration algorithms."
+description: "Use when user asks to \"deep review the code\", \"thorough code review\", \"multi-pass review\", or when orchestrating the Phase 9 review loop. Provides review pass definitions (code quality, security, performance, test coverage), signal detection patterns, and iteration algorithms."
 metadata:
   short-description: "Multi-pass code review orchestration"
 ---
diff --git a/adapters/opencode/skills/validate-delivery/SKILL.md b/adapters/opencode/skills/validate-delivery/SKILL.md
@@ -1,7 +1,7 @@
 <!-- AUTO-GENERATED by scripts/gen-adapters.js - DO NOT EDIT -->
 ---
 name: validate-delivery
-description: "Use when validating task completion before shipping. Runs tests, build, and requirement checks. Returns pass/fail with fix instructions."
+description: "Use when user asks to \"validate delivery\", \"check readiness\", or \"verify completion\". Runs tests, build, and requirement checks with pass/fail instructions."
 version: 5.0.0
 ---
 
diff --git a/plugins/next-task/skills/discover-tasks/SKILL.md b/plugins/next-task/skills/discover-tasks/SKILL.md
@@ -1,6 +1,6 @@
 ---
 name: discover-tasks
-description: "Use when discovering and prioritizing tasks from configured sources. Handles GitHub, GitLab, local files, and custom sources."
+description: "Use when user asks to \"discover tasks\", \"find next task\", or \"prioritize issues\". Discovers and ranks tasks from GitHub, GitLab, local files, and custom sources."
 version: 5.0.0
 ---
 
diff --git a/plugins/next-task/skills/orchestrate-review/SKILL.md b/plugins/next-task/skills/orchestrate-review/SKILL.md
@@ -1,6 +1,6 @@
 ---
 name: orchestrate-review
-description: "Use when user asks to \"deep review the code\", \"thorough code review\", \"multi-pass review\", or when orchestrating Phase 9 review loop. Provides review pass definitions (code quality, security, performance, test coverage, specialists), signal detection patterns, and iteration algorithms."
+description: "Use when user asks to \"deep review the code\", \"thorough code review\", \"multi-pass review\", or when orchestrating the Phase 9 review loop. Provides review pass definitions (code quality, security, performance, test coverage), signal detection patterns, and iteration algorithms."
 metadata:
   short-description: "Multi-pass code review orchestration"
 ---
diff --git a/plugins/next-task/skills/validate-delivery/SKILL.md b/plugins/next-task/skills/validate-delivery/SKILL.md
@@ -1,6 +1,6 @@
 ---
 name: validate-delivery
-description: "Use when validating task completion before shipping. Runs tests, build, and requirement checks. Returns pass/fail with fix instructions."
+description: "Use when user asks to \"validate delivery\", \"check readiness\", or \"verify completion\". Runs tests, build, and requirement checks with pass/fail instructions."
 version: 5.0.0
 ---
 
PATCH

echo "Gold patch applied."
