"""Behavioral checks for prefect-exclude-autogenerated-docs-from-documentchanges (markdown_authoring task).

Each test asserts that a distinctive literal from the gold patch appears
in the target tier-1 file after the agent runs.
"""
from __future__ import annotations

from pathlib import Path

REPO = Path("/workspace/prefect")


def _read(path: str) -> str:
    p = REPO / path
    assert p.is_file(), f"{p} does not exist"
    return p.read_text(encoding="utf-8", errors="replace")


def test_signal_00():
    """Distinctive line from gold patch must be present."""
    text = _read('.claude/skills/document-changes/SKILL.md')
    assert "- **Don't touch auto-generated pages.** Skip the entire `docs/v3/api-ref/` directory (including `settings-ref.mdx`, Python SDK reference, CLI reference, and REST API reference), the entire `docs/v3/ex" in text, "expected to find: " + "- **Don't touch auto-generated pages.** Skip the entire `docs/v3/api-ref/` directory (including `settings-ref.mdx`, Python SDK reference, CLI reference, and REST API reference), the entire `docs/v3/ex"[:80]


def test_signal_01():
    """Distinctive line from gold patch must be present."""
    text = _read('.claude/skills/document-changes/SKILL.md')
    assert '**Exclude auto-generated files.** Before searching or editing, filter out all auto-generated doc files. These are maintained by generation scripts and will be updated separately before each release. N' in text, "expected to find: " + '**Exclude auto-generated files.** Before searching or editing, filter out all auto-generated doc files. These are maintained by generation scripts and will be updated separately before each release. N'[:80]


def test_signal_02():
    """Distinctive line from gold patch must be present."""
    text = _read('.claude/skills/document-changes/SKILL.md')
    assert '- Skip any file under an auto-generated path (`docs/v3/api-ref/`, `docs/v3/examples/`) or containing a generated-by comment — do not edit these even if they appear stale' in text, "expected to find: " + '- Skip any file under an auto-generated path (`docs/v3/api-ref/`, `docs/v3/examples/`) or containing a generated-by comment — do not edit these even if they appear stale'[:80]

