"""Behavioral checks for templates-docs-improve-agentsmd-file (markdown_authoring task).

Each test asserts that a distinctive literal from the gold patch appears
in the target tier-1 file after the agent runs.
"""
from __future__ import annotations

from pathlib import Path

REPO = Path("/workspace/templates")


def _read(path: str) -> str:
    p = REPO / path
    assert p.is_file(), f"{p} does not exist"
    return p.read_text(encoding="utf-8", errors="replace")


def test_signal_00():
    """Distinctive line from gold patch must be present."""
    text = _read('AGENTS.md')
    assert '**IMPORTANT:** AI tools **MUST NEVER** fabricate or hallucinate "Online Editor test results" links. These must be generated by actually using the [Online Editor](https://domainconnect.paulonet.eu/dc/f' in text, "expected to find: " + '**IMPORTANT:** AI tools **MUST NEVER** fabricate or hallucinate "Online Editor test results" links. These must be generated by actually using the [Online Editor](https://domainconnect.paulonet.eu/dc/f'[:80]


def test_signal_01():
    """Distinctive line from gold patch must be present."""
    text = _read('AGENTS.md')
    assert 'The commit body should follow the structure defined in [`.github/pull_request_template.md`](.github/pull_request_template.md). When creating commit messages, AI tools may:' in text, "expected to find: " + 'The commit body should follow the structure defined in [`.github/pull_request_template.md`](.github/pull_request_template.md). When creating commit messages, AI tools may:'[:80]


def test_signal_02():
    """Distinctive line from gold patch must be present."""
    text = _read('AGENTS.md')
    assert '- **New template:** `add <providerName>, <serviceName>` (e.g., `add Example Domain Connect Service, Stateless Hosting Primary`)' in text, "expected to find: " + '- **New template:** `add <providerName>, <serviceName>` (e.g., `add Example Domain Connect Service, Stateless Hosting Primary`)'[:80]

