#!/usr/bin/env bash
set -euo pipefail

cd /workspace/perfetto

# Idempotency guard
if grep -qF "- Other target names are usually: traced, traced_probes, perfetto, trace_process" "AGENTS.md"; then
  echo "Gold patch already applied."
  exit 0
fi

git apply --whitespace=nowarn <<'PATCH'
diff --git a/AGENTS.md b/AGENTS.md
@@ -9,32 +9,75 @@ quality.
 Use the following commands to build the project for different configurations.
 All commands should be run from the root of the repository.
 
-### Standard Release Build
+The output folder where code is built lives in out/xxx. Different people use
+different output folders. Pick the output folder as follows
+- The $OUT env var should contain the path of the output folder. If it exists respect that.
+- If $OUT is empty/unset, set it by looking at the most recent out/ subdir, i.e.
+  `OUT=out/$(ls -t1 out | head -n1)`
 
-To build the standard release version:
+### Building C++ code
+
+Our C++ sources use tools/gn and tools/ninja to build.
+
+- If you touch a .gn or .gni file, rerun `tools/gn gen --check $OUT`
+- Afterwards, you can build code running `tools/ninja -C $OUT TARGET_NAME"
+- TARGET_NAME is:
+  - perfetto_unittests: for any file in src/**/*_unittest.cc
+  - perfetto_integrationtests: for any file in src/**/*_integrationtest.cc (and most code under test/)
+  - perfetto_benchmarks: for any file in src/**/*_benchmark.cc (and most code under test/)
+  - Other target names are usually: traced, traced_probes, perfetto, trace_processor_shell. You can discover them following the root /BUILD.gn file
+
+When adding/removing source files, keep BUILD.gn files updated.
+Usually there is a BUILD.gn file in each directory. If not, look at closer parent dirs for precedent.
+
+Never bother manually updating Android.bp files or bazel BUILD files.
+Those are autogenerated later when uploading the pull request via
+`tools/gen_all $OUT`, but humans will take care of that.
+
+To build one or more targets:
 
 ```sh
-tools/ninja -C out/linux_clang_release -k 10000 trace_processor_shell perfetto_unittests
+tools/ninja -C $OUT -k 10000 trace_processor_shell perfetto_unittests
 ```
 
-## 2. Running Tests
+### 2. Running C++ Tests
 
-Use the following commands to run unit tests for the corresponding build
-configurations.
+Perfetto uses the Google Test framework. You will see c++ sources like
+```cpp
+TEST(ProtozeroToJsonTest, Foo) {
+...
+}
+```
+
+ProtozeroToJsonTest is the test suite name, Foo the test name.
+
+You can run all the tests in a test suite by doing:
 
-### Standard Release Tests
+```sh
+$OUT/perfetto_unittests --gtest_brief=1 --gtest_filter="ProtozeroToJsonTest.*"
+```
 
+Or if you touch a specific test, you can run only that one doing
 ```sh
-out/linux_clang_release/perfetto_unittests --gtest_brief=1 --gtest_filter="<TestSuiteName.*>"
+$OUT/perfetto_unittests --gtest_brief=1 --gtest_filter="ProtozeroToJsonTest.Foo"
 ```
+Same goes for perfetto_integrationtests.
+
+For perfetto_benchmarks you need instead to run
+
+```sh
+$OUT/perfetto_benchmarks --benchmark_filter='.*BM_RtMutex_NoContention.*'
+```
+
+Note that unlike Google Test, where the filter is a glob, in Google Benchmarks the filter is a regex.
 
 ### Trace Processor Diff Tests
 
 Trace Processor Diff Tests (or diff tests for short) are executed by running the
 following command:
 
 ```sh
-tools/diff_test_trace_processor.py out/linux_clang_release/trace_processor_shell --keep-input --quiet --name-filter="<regex of test names>"
+tools/diff_test_trace_processor.py $OUT$/trace_processor_shell --keep-input --quiet --name-filter="<regex of test names>"
 ```
 
 **Note:** These tests can also be run with ASan or MSan builds by changing the
@@ -44,14 +87,6 @@ using the `--name-filter` flag, do not include `test_` in the filter. The test
 runner automatically drops this prefix. For example, to run `test_my_cool_test`,
 use the filter `MyTestSuite.my_cool_test`.
 
-### Integration Tests
-
-Integration tests are executed by running the `perfetto_integrationtests`
-binary. For example:
-
-```sh
-out/linux_clang_release/perfetto_integrationtests --gtest_filter="<TestSuiteName.*>"
-```
 
 ### Test Guidelines
 
@@ -97,7 +132,7 @@ When asked to fix GN dependencies, run the following command and fix any errors
 that are reported:
 
 ```sh
-tools/gn check out/linux_clang_release/
+tools/gn check $OUT
 ```
 
 **Note:** When fixing include errors, do not add dependencies to `public_deps`
PATCH

echo "Gold patch applied."
