#!/bin/bash
set -e

cd /workspace/langchain

# Check if already patched (idempotency check)
if grep -q "LC_AUTOGENERATED" libs/core/langchain_core/messages/block_translators/openai.py 2>/dev/null; then
    echo "Patch already applied, skipping"
    exit 0
fi

# Apply the gold patch
cat <<'PATCH' | git apply -
diff --git a/libs/core/langchain_core/messages/block_translators/openai.py b/libs/core/langchain_core/messages/block_translators/openai.py
index 2a7ca0f5c8..5b7a8e3c9a 100644
--- a/libs/core/langchain_core/messages/block_translators/openai.py
+++ b/libs/core/langchain_core/messages/block_translators/openai.py
@@ -103,11 +103,13 @@ def convert_to_openai_data_block(
                 # Backward compat
                 file["filename"] = extras["filename"]
             else:
-                # Can't infer filename
+                # Can't infer filename; set a placeholder default for compatibility.
+                file["filename"] = "LC_AUTOGENERATED"
                 warnings.warn(
                     "OpenAI may require a filename for file uploads. Specify a filename"
                     " in the content block, e.g.: {'type': 'file', 'mime_type': "
-                    "'...', 'base64': '...', 'filename': 'my-file.pdf'}",
+                    "'...', 'base64': '...', 'filename': 'my-file.pdf'}. "
+                    "Using placeholder filename 'LC_AUTOGENERATED'.",
                     stacklevel=1,
                 )
             formatted_block = {"type": "file", "file": file}
PATCH

echo "Patch applied successfully"
