"""
Task: mlflow-fetchdiff-mask-autogenerated-files
Repo: mlflow/mlflow @ 33200f3a6208bee42c5c1c10a4687bc78302b9a8
PR:   22340

All checks must pass for reward = 1. Any failure = reward 0.
Each test function maps 1:1 to a check in eval_manifest.yaml.
"""

import json
import subprocess
import sys
from pathlib import Path

REPO = "/workspace/mlflow"
FETCH_DIFF_PY = Path(REPO) / ".claude/skills/src/skills/commands/fetch_diff.py"
SKILL_MD = Path(REPO) / ".claude/skills/fetch-diff/SKILL.md"

# Sample diffs for behavioral tests
LOCK_FILE_DIFF = (
    "diff --git a/uv.lock b/uv.lock\n"
    "index abc123..def456 100644\n"
    "--- a/uv.lock\n"
    "+++ b/uv.lock\n"
    "@@ -1,3 +1,3 @@\n"
    "-old_lock_content\n"
    "+new_lock_content\n"
    " unchanged\n"
)

REGULAR_FILE_DIFF = (
    "diff --git a/src/main.py b/src/main.py\n"
    "index abc123..def456 100644\n"
    "--- a/src/main.py\n"
    "+++ b/src/main.py\n"
    "@@ -1,3 +1,3 @@\n"
    "-old_code\n"
    "+new_code\n"
    " unchanged\n"
)

NOTEBOOK_DIFF = (
    "diff --git a/demo.ipynb b/demo.ipynb\n"
    "index abc123..def456 100644\n"
    "--- a/demo.ipynb\n"
    "+++ b/demo.ipynb\n"
    "@@ -1,3 +1,3 @@\n"
    '-{"cells": []}\n'
    '+{"cells": [1]}\n'
    " unchanged\n"
)

MULTI_HUNK_LOCK_DIFF = (
    "diff --git a/uv.lock b/uv.lock\n"
    "index abc123..def456 100644\n"
    "--- a/uv.lock\n"
    "+++ b/uv.lock\n"
    "@@ -1,3 +1,3 @@\n"
    "-old1\n"
    "+new1\n"
    " unchanged1\n"
    "@@ -10,3 +10,3 @@\n"
    "-old2\n"
    "+new2\n"
    " unchanged2\n"
)


def _run_filter_diff(script_body: str, timeout: int = 30) -> subprocess.CompletedProcess:
    """Run a Python script that imports filter_diff with mocked dependencies."""
    setup = (
        "import sys, types\n"
        "sys.path.insert(0, '.claude/skills/src')\n"
        # Pre-register skills.github mock before import so fetch_diff.py
        # doesn't try to import aiohttp/httpx (not installed in test image)
        "import skills\n"
        "github_mod = types.ModuleType('skills.github')\n"
        "github_mod.GitHubClient = None\n"
        "github_mod.parse_pr_url = None\n"
        "sys.modules['skills.github'] = github_mod\n"
        "from skills.commands.fetch_diff import filter_diff\n"
    )
    full_script = setup + script_body
    return subprocess.run(
        [sys.executable, "-c", full_script],
        capture_output=True, text=True, timeout=timeout, cwd=REPO,
    )


# ---------------------------------------------------------------------------
# Gates (pass_to_pass, static)
# ---------------------------------------------------------------------------

# [static] pass_to_pass
def test_syntax_check():
    """Modified files must parse without errors."""
    import py_compile
    py_compile.compile(str(FETCH_DIFF_PY), doraise=True)


# ---------------------------------------------------------------------------
# Fail-to-pass (pr_diff) — core behavioral tests
# ---------------------------------------------------------------------------

# [pr_diff] fail_to_pass
def test_autogenerated_shown_with_mask():
    """Auto-generated files (e.g. uv.lock) appear in output with masked content."""
    diff_input = LOCK_FILE_DIFF + REGULAR_FILE_DIFF
    r = _run_filter_diff(
        "import json, sys\n"
        f"diff_input = {json.dumps(diff_input)}\n"
        "result = filter_diff(diff_input)\n"
        "print(json.dumps({'result': result}))\n"
    )
    assert r.returncode == 0, f"Script failed: {r.stderr}"
    data = json.loads(r.stdout.strip())
    result = data["result"]
    # uv.lock must appear in output (not excluded)
    assert "uv.lock" in result, "uv.lock should appear in filtered output"
    # The mask message must be present
    assert "[Auto-generated file - diff masked]" in result, (
        "Auto-generated file should show masked diff message"
    )
    # Actual hunk content should NOT appear for the lock file
    assert "old_lock_content" not in result, "Lock file hunk content should be masked"
    assert "new_lock_content" not in result, "Lock file hunk content should be masked"
    # Regular file content should still appear
    assert "new_code" in result, "Regular file content should be preserved"


# [pr_diff] fail_to_pass
def test_ipynb_no_longer_excluded():
    """Notebook files (.ipynb) are no longer excluded from diff output."""
    r = _run_filter_diff(
        "import json, sys\n"
        f"diff_input = {json.dumps(NOTEBOOK_DIFF)}\n"
        "result = filter_diff(diff_input)\n"
        "print(json.dumps({'result': result}))\n"
    )
    assert r.returncode == 0, f"Script failed: {r.stderr}"
    data = json.loads(r.stdout.strip())
    result = data["result"]
    assert "demo.ipynb" in result, "Notebook file should appear in diff output"


# [pr_diff] fail_to_pass
def test_mask_only_once_for_multi_hunk():
    """Auto-generated file with multiple hunks shows mask message only once."""
    r = _run_filter_diff(
        "import json, sys\n"
        f"diff_input = {json.dumps(MULTI_HUNK_LOCK_DIFF)}\n"
        "result = filter_diff(diff_input)\n"
        "print(json.dumps({'result': result}))\n"
    )
    assert r.returncode == 0, f"Script failed: {r.stderr}"
    data = json.loads(r.stdout.strip())
    result = data["result"]
    mask_msg = "[Auto-generated file - diff masked]"
    assert result.count(mask_msg) == 1, (
        f"Mask message should appear exactly once, found {result.count(mask_msg)}"
    )
    # Hunk content must not leak
    assert "old1" not in result
    assert "new2" not in result


# ---------------------------------------------------------------------------
# Pass-to-pass (static) — regression
# ---------------------------------------------------------------------------

# [static] pass_to_pass
def test_regular_file_line_numbers():
    """Regular files still get line number annotations in output."""
    r = _run_filter_diff(
        "import json, sys\n"
        f"diff_input = {json.dumps(REGULAR_FILE_DIFF)}\n"
        "result = filter_diff(diff_input)\n"
        "print(json.dumps({'result': result}))\n"
    )
    assert r.returncode == 0, f"Script failed: {r.stderr}"
    data = json.loads(r.stdout.strip())
    result = data["result"]
    # Line numbers should be present (old_line and/or new_line columns)
    assert "| -old_code" in result, "Deleted line should have line number annotation"
    assert "| +new_code" in result, "Added line should have line number annotation"


# ---------------------------------------------------------------------------
# Config file update tests (pr_diff)
# ---------------------------------------------------------------------------

# [pr_diff] fail_to_pass
def test_skill_md_documents_masked_output():
    """SKILL.md must document the masked diff behavior for auto-generated files."""
    content = SKILL_MD.read_text()
    # The description should mention masked diffs (not "filters out")
    assert "mask" in content.lower(), (
        "SKILL.md should describe masked diff behavior"
    )
    # Should include an example of the masked output
    assert "[Auto-generated file" in content or "auto-generated" in content.lower(), (
        "SKILL.md should document auto-generated file handling"
    )
    # Should NOT say auto-generated files are excluded/filtered out
    assert "filters out auto-generated" not in content.lower(), (
        "SKILL.md should no longer say auto-generated files are filtered out"
    )


# [pr_diff] fail_to_pass
def test_function_renamed_to_is_autogenerated():
    """should_exclude_file renamed to is_autogenerated_file."""
    source = FETCH_DIFF_PY.read_text()
    assert "def is_autogenerated_file(" in source, (
        "Function should be renamed to is_autogenerated_file"
    )
    assert "def should_exclude_file(" not in source, (
        "Old function name should_exclude_file should not exist"
    )
