#!/usr/bin/env bash
set -euo pipefail

cd /workspace/hardwarevisualizer

# Idempotency guard
if grep -qF "- If OS APIs / DB / external I/O are involved, also add/change `src-tauri/src/in" ".github/copilot-instructions.md" && grep -qF "Frontend \u2194 backend communication is done via **Tauri commands**; TypeScript bind" "AGENTS.md"; then
  echo "Gold patch already applied."
  exit 0
fi

git apply --whitespace=nowarn <<'PATCH'
diff --git a/.github/copilot-instructions.md b/.github/copilot-instructions.md
@@ -1,74 +1,46 @@
-# Copilot Instructions for HardwareVisualizer
-
-## Overview
-
-HardwareVisualizer は、リアルタイムでコンピュータのハードウェアパフォーマンスを監視するツールです。このプロジェクトは、フロントエンド（TypeScript/React）とバックエンド（Rust/Tauri）で構成されています。以下のガイドラインは、AI コーディングエージェントがこのコードベースで効率的に作業するための指針を提供します。
-
-## プロジェクト構造
-
-- **`src/`**: フロントエンドの主要なコードが含まれています。
-  - `components/`: 再利用可能な UI コンポーネント。
-  - `features/`: 機能ごとのモジュール（例: hardware, menu, settings）。
-  - `hooks/`: React カスタムフック。
-  - `lib/`: ユーティリティ関数。
-  - `store/`: 状態管理関連のコード。
-  - `types/`: TypeScript 型定義。
-- **`src-tauri/`**: バックエンドの Rust コード。
-  - `src/`: Rust の主要なコード。
-  - `commands/`: フロントエンドと通信するための Tauri コマンド。
-  - `database/`: データベース関連のロジック。
-  - `services/`: サービス層のロジック。
-  - `utils/`: ユーティリティ関数。
-- **`test/`**: 単体テスト。
-- **`coverage/`**: テストカバレッジレポート。
-
-## 開発フロー
-
-### 必要なツール
-
-- Node.js v22
-- Rust 1.85
-
-### コマンド
-
-- **依存関係のインストール**:
-  ```bash
-  npm ci
-  ```
-- **開発モードでの起動**:
-  ```bash
-  npm run tauri dev
-  ```
-- **本番ビルド**:
-  ```bash
-  npm run tauri build
-  ```
-- **コードのリント**:
-  ```bash
-  npm run lint
-  cargo clippy --manifest-path src-tauri/Cargo.toml -- -D warnings
-  ```
-- **コードのフォーマット**:
-  ```bash
-  npm run format
-  cargo fmt --manifest-path src-tauri/Cargo.toml -- --check
-  ```
-- **テストの実行**:
-
-  ```bash
-  npm test
-  cargo test --manifest-path src-tauri/Cargo.toml -- --test-threads=1 --nocapture
-  ```
-
-## プロジェクト固有のパターン
-
-- **Tauri コマンド**: フロントエンドとバックエンド間の通信は、`src-tauri/src/commands/` 内のコマンドを使用して行われます。フロントエンドからは、自動生成された `rspc/bindings.ts` を通じて Tauri コマンドを呼び出します。
-- **ユーティリティ関数**: 再利用可能なロジックは `lib/` または `src-tauri/src/utils/` に配置されています。
-
-## 参考ファイル
-
-- `README.md`: プロジェクトの全体像とセットアップ手順。
-- `vite.config.ts`: フロントエンドのビルド設定。
-- `tauri.conf.json`: Tauri アプリケーションの設定。
-
-このガイドラインに基づいて作業を進めてください。不明点があれば、README.md やコードベースを参照してください。
+# HardwareVisualizer – Copilot Coding Agent Instructions
+
+## Big picture
+- Cross-platform hardware monitoring app (React/Vite + Tauri/Rust).
+- Frontend ↔ backend calls go through **Tauri commands**. `src/rspc/bindings.ts` is **generated by tauri-specta** (do not edit).
+- Rust backend follows strict one-way dependencies: **Commands → Services → Platform (Factory) → OS APIs** (see `docs/ARCHITECTURE/BACKEND_ARCHITECTURE.md`).
+
+## Where to change code
+- UI/features: `src/features/**` (e.g. `src/features/settings/hooks/useSettingsAtom.ts`). Shared UI lives in `src/components/ui/**` (shadcn/Radix).
+- State management uses **Jotai**: define with `atom(...)`, consume with `useAtom(...)` (e.g. `src/features/hardware/hooks/useHardwareInfoAtom.ts`).
+- Lightweight persisted UI settings: Tauri Store plugin.
+  - Store instance: `src/lib/tauriStore.ts`
+  - Hook: `src/hooks/useTauriStore.ts` (returns a union of `[value|null, setValue, isPending]`)
+
+## Backend/Frontend integration
+- Call commands via `import { commands } from "@/rspc/bindings"`.
+- Check `Result` with `isError(...)` (e.g. `src/features/hardware/hooks/useHardwareInfoAtom.ts`). On failure, notify via `useTauriDialog().error(...)`.
+- When adding a new backend command:
+  - Add code in `src-tauri/src/commands/*.rs` (UI boundary) → `src-tauri/src/services/*.rs` (business logic) → `src-tauri/src/platform/**` (OS-specific)
+  - If OS APIs / DB / external I/O are involved, also add/change `src-tauri/src/infrastructure/**` (e.g. `infrastructure/providers/**`, `infrastructure/database/**`)
+  - Register it in `collect_commands![ ... ]` inside `src-tauri/src/lib.rs` (this drives TS bindings generation)
+  - `src/rspc/bindings.ts` is exported from `src-tauri/src/lib.rs` in debug builds; regenerate via `npm run tauri dev`
+
+## Error/event conventions
+- Backend emits `error_event`; frontend shows a modal via `useErrorModalListener` (see `src/hooks/useTauriEventListener.ts`).
+
+## Dev workflows (repo-specific)
+- Prereqs: Node.js v22 (per README) + Rust (toolchain in `rust-toolchain.toml`).
+- Linux build deps: `libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf` (see CI/README). Some metrics require sudo.
+- Web UI only: `npm run dev` (React DevTools + Vite). Vite port is fixed to `1520` (`vite.config.ts`).
+- Desktop (Tauri): `npm run tauri dev`
+- Frontend lint/format: `npm run lint` / `npm run format` (Biome; primarily targets `./src`)
+- Frontend tests: `npm test` (Vitest; config in `vitest.config.ts` / setup in `src/test/setup.ts`)
+- Rust checks (CI parity):
+  - `cargo fmt --manifest-path src-tauri/Cargo.toml -- --check`
+  - `cargo clippy --manifest-path src-tauri/Cargo.toml -- -D warnings`
+  - `cargo test --manifest-path src-tauri/Cargo.toml -- --test-threads=1 --nocapture`
+
+## Project conventions
+- Import alias: `@` → `src` (`vite.config.ts` / `vitest.config.ts`).
+- i18n: `src/lib/i18n.ts` with `src/lang/en.json` and `src/lang/ja.json`. Add UI strings to JSON and reference via `useTranslation()` (e.g. `src/App.tsx`).
+- Avoid editing generated/vendor outputs: do not edit `src/rspc/bindings.ts`.
+
+## Communication
+- Write code comments and git commit messages in English.
+- In chat, match the language used in the user prompt.
diff --git a/AGENTS.md b/AGENTS.md
@@ -4,6 +4,8 @@
 
 **HardwareVisualizer** is a cross-platform hardware monitoring application built with Tauri (Rust + React/TypeScript). It provides real-time hardware performance monitoring with customizable dashboards, detailed usage graphs, and historical data insights.
 
+Frontend ↔ backend communication is done via **Tauri commands**; TypeScript bindings are generated (see `src/rspc/bindings.ts`, do not edit manually).
+
 ## Tech Stack
 
 - **Frontend**: React 19, TypeScript, Tailwind CSS 4.x, Vite 7
@@ -33,12 +35,14 @@
 │   │   ├── platform/     # Platform abstraction layer
 │   │   │   ├── traits.rs # Common interfaces
 │   │   │   ├── factory.rs # Platform selection
-│   │   │   ├── common/   # Shared utilities
 │   │   │   ├── windows/  # Windows-specific implementations
 │   │   │   ├── linux/    # Linux-specific implementations
 │   │   │   └── macos/    # macOS-specific implementations
-│   │   ├── structs/      # Data type definitions
+│   │   ├── models/       # Data type definitions
+│   │   ├── enums/        # Type definitions (including error types)
+│   │   ├── infrastructure/ # External resources (providers, database)
 │   │   ├── utils/        # Utility functions
+│   │   ├── workers/      # Background tasks (monitoring, archive, updater)
 │   │   └── _tests/       # Test modules
 │   └── capabilities/     # Tauri permissions
 |── .github/               # GitHub Actions workflows
@@ -60,6 +64,11 @@
 | `npm run format`    | Format code with Biome                       |
 | `npm test`          | Run frontend tests with coverage             |
 
+## Communication
+
+- Write code comments and git commit messages in English.
+- In chat, match the language used in the user prompt.
+
 ## Code Quality Standards
 
 ### Linting & Formatting
@@ -72,22 +81,14 @@
 
 - **Unit Tests**: Vitest for frontend, Cargo test for Rust
 - **Coverage**: Aim for comprehensive test coverage
-- **Test Location**: `/test/unit/` for frontend, `/src-tauri/src/_tests/` for Rust
+- **Test Location**: `src/test/unit/` for frontend, `src-tauri/src/_tests/` for Rust
 
 ### TypeScript Configuration
 
 - Strict TypeScript enabled
 - Path aliases configured for clean imports
 - Custom types in `/src/types/`
 
-## Platform Support
-
-| Platform | Status       | Requirements            |
-| -------- | ------------ | ----------------------- |
-| Windows  | ✅ Supported | WebView2                |
-| Linux    | ✅ Supported | webkit2gtk, sudo access |
-| macOS    | 🔒 Planned   | No ETA                  |
-
 ## Architecture Design
 
 ### Layered Architecture Pattern
@@ -98,22 +99,24 @@ The backend follows a strict layered architecture with unidirectional dependenci
 Commands → Services → Platform (via Factory) → OS APIs
 ```
 
+If OS APIs / DB / external I/O are involved, services typically also rely on `src-tauri/src/infrastructure/**`.
+
 #### Layer Responsibilities
 
-1. **Commands Layer** (`src/commands/`)
+1. **Commands Layer** (`src-tauri/src/commands/`)
 
    - Tauri command handlers (UI interface)
    - Input validation and output formatting
    - Delegates to services layer for business logic
 
-2. **Services Layer** (`src/services/`)
+2. **Services Layer** (`src-tauri/src/services/`)
 
    - Application business logic and hardware data processing
    - Platform abstraction through Factory pattern
    - Hardware monitoring state management
    - Data aggregation and formatting
 
-3. **Platform Layer** (`src/platform/`)
+3. **Platform Layer** (`src-tauri/src/platform/`)
    - OS-specific hardware access implementations
    - Trait-based platform abstraction (`MemoryPlatform`, `GpuPlatform`, `NetworkPlatform`)
    - Factory pattern for automatic platform detection
@@ -239,6 +242,12 @@ impl PlatformFactory {
 - **Error Handling**: Comprehensive error boundaries and logging
 - **Internationalization**: i18next for multi-language support
 
+## Frontend conventions worth knowing
+
+- Generated bindings: `src/rspc/bindings.ts` is generated by tauri-specta; edit Rust commands and re-run `npm run tauri dev` to regenerate.
+- Persistent UI settings: Tauri Store plugin via `src/lib/tauriStore.ts` + `src/hooks/useTauriStore.ts`.
+- Error events: backend emits `error_event`; frontend listens via `useErrorModalListener` in `src/hooks/useTauriEventListener.ts`.
+
 ## Security Considerations
 
 - **Tauri CSP**: Configured for secure WebView
PATCH

echo "Gold patch applied."
