#!/usr/bin/env bash
# Gold solution for: make Tracing.group return Disposable
set -euo pipefail

cd /workspace/playwright

# Idempotency: bail out if the patch is already applied.
if grep -q "return new DisposableStub(() => this.groupEnd());" \
        packages/playwright-core/src/client/tracing.ts; then
    echo "Patch already applied; skipping."
    exit 0
fi

# Apply the gold patch (inlined; no external fetch).
git apply <<'PATCH'
diff --git a/docs/src/api/class-tracing.md b/docs/src/api/class-tracing.md
--- a/docs/src/api/class-tracing.md
+++ b/docs/src/api/class-tracing.md
@@ -305,6 +305,7 @@

 ## async method: Tracing.group
 * since: v1.49
+- returns: <[Disposable]>

 :::caution
 Use `test.step` instead when available.
diff --git a/packages/playwright-core/src/client/tracing.ts b/packages/playwright-core/src/client/tracing.ts
--- a/packages/playwright-core/src/client/tracing.ts
+++ b/packages/playwright-core/src/client/tracing.ts
@@ -16,6 +16,7 @@

 import { Artifact } from './artifact';
 import { ChannelOwner } from './channelOwner';
+import { DisposableStub } from './disposable';

 import type * as api from '../../types/types';
 import type * as channels from '@protocol/channels';
@@ -62,6 +63,7 @@ export class Tracing extends ChannelOwner<channels.TracingChannel> implements ap
     if (options.location)
       this._additionalSources.add(options.location.file);
     await this._channel.tracingGroup({ name, location: options.location });
+    return new DisposableStub(() => this.groupEnd());
   }

   async groupEnd() {
PATCH

echo "Patch applied. Source files updated; types/lib will be regenerated by test.sh."
