#!/usr/bin/env bash
set -euo pipefail

cd /workspace/prefect

# Idempotency guard
if grep -qF "- **Don't touch auto-generated pages.** Skip the entire `docs/v3/api-ref/` direc" ".claude/skills/document-changes/SKILL.md"; then
  echo "Gold patch already applied."
  exit 0
fi

git apply --whitespace=nowarn <<'PATCH'
diff --git a/.claude/skills/document-changes/SKILL.md b/.claude/skills/document-changes/SKILL.md
@@ -74,8 +74,13 @@ Scan the diff for changes that users would encounter:
 
 For each extracted change, search the docs for references. Use parallel searches for efficiency.
 
+**Exclude auto-generated files.** Before searching or editing, filter out all auto-generated doc files. These are maintained by generation scripts and will be updated separately before each release. Never search, flag, or edit these paths:
+- `docs/v3/api-ref/` — entire directory (generated by `scripts/generate_api_ref.py` and `scripts/generate_settings_ref.py`)
+- `docs/v3/examples/` — entire directory (generated by `scripts/generate_example_pages.py`)
+- Any file containing a comment like `This page is generated by` or `automatically generated`
+
 **Search strategy:**
-- Grep `docs/` for function names, class names, CLI command names, setting names
+- Grep `docs/` (excluding auto-generated paths above) for function names, class names, CLI command names, setting names
 - Check concept pages that explain the changed feature's behavior
 - Check how-to guides that demonstrate the changed API
 - Check get-started pages if fundamental APIs changed
@@ -139,6 +144,7 @@ After presenting the report, offer:
 #### Edit mode (CI)
 
 Directly apply fixes for **Stale** and **Broken example** findings on existing pages:
+- Skip any file under an auto-generated path (`docs/v3/api-ref/`, `docs/v3/examples/`) or containing a generated-by comment — do not edit these even if they appear stale
 - Read each affected doc file
 - Make targeted, minimal edits to fix the specific issues
 - Do not rewrite surrounding content
@@ -172,5 +178,5 @@ After applying fixes (if the user chose to), mention:
 - **Verify before flagging.** Read both the diff and the current doc file. A grep hit doesn't mean the doc is wrong — read the context.
 - **Respect doc scope.** Not every public API needs docs. Flag missing coverage for features users would reasonably expect to find documented, not for every internal helper that happens to be public.
 - **Minimize blast radius in CI.** Small, targeted fixes only. If a finding requires judgment about page structure or new content, leave it as a recommendation rather than an automated edit.
-- **Don't touch auto-generated pages.** Skip `v3/examples/`, `v3/api-ref/`, and any file noted as auto-generated.
+- **Don't touch auto-generated pages.** Skip the entire `docs/v3/api-ref/` directory (including `settings-ref.mdx`, Python SDK reference, CLI reference, and REST API reference), the entire `docs/v3/examples/` directory, and any file containing a generated-by comment (e.g., `This page is generated by`). These files are regenerated by scripts before each release and must not be edited manually or by automation.
 - **Check code block test directives.** If you modify a code block, check whether it has `pmd-metadata` directives and preserve them. If you're unsure whether a modified block is testable, mark it `notest` and note why.
PATCH

echo "Gold patch applied."
