"""
Task: mlflow-fetchdiff-show-deleted-files-masked
Repo: mlflow/mlflow @ dcc138b281ea230b18215dfe839c297076337adc
PR:   22341

All checks must pass for reward = 1. Any failure = reward 0.
Each test function maps 1:1 to a check in eval_manifest.yaml.
"""

import subprocess
import sys
import types
from pathlib import Path

REPO = "/workspace/mlflow"


def _import_fetch_diff():
    """Import filter_diff by mocking unavailable dependencies."""
    # Mock the skills.github module so fetch_diff.py can be imported
    src_path = f"{REPO}/.claude/skills/src"
    skills_mod = types.ModuleType("skills")
    skills_mod.__path__ = [f"{src_path}/skills"]
    github_mod = types.ModuleType("skills.github")
    github_mod.GitHubClient = None
    github_mod.parse_pr_url = None
    commands_mod = types.ModuleType("skills.commands")
    commands_mod.__path__ = [f"{src_path}/skills/commands"]
    sys.modules.setdefault("skills", skills_mod)
    sys.modules.setdefault("skills.github", github_mod)
    sys.modules.setdefault("skills.commands", commands_mod)
    sys.path.insert(0, src_path)
    from skills.commands.fetch_diff import filter_diff
    return filter_diff


# Sample diffs for testing
DELETED_FILE_DIFF = """\
diff --git a/path/to/removed.py b/dev/null
deleted file mode 100644
index abc1234..0000000
--- a/path/to/removed.py
+++ /dev/null
@@ -1,3 +0,0 @@
-import os
-def hello():
-    print("hello")"""

REGULAR_FILE_DIFF = """\
diff --git a/src/main.py b/src/main.py
index aaa1111..bbb2222 100644
--- a/src/main.py
+++ b/src/main.py
@@ -10,3 +10,4 @@
 import os
 import sys
+import json
 def main():"""

AUTOGENERATED_DIFF = """\
diff --git a/uv.lock b/uv.lock
index ccc3333..ddd4444 100644
--- a/uv.lock
+++ b/uv.lock
@@ -1,3 +1,4 @@
 line1
 line2
+line3
 line4"""

MIXED_DIFF = DELETED_FILE_DIFF + "\n" + REGULAR_FILE_DIFF


# ---------------------------------------------------------------------------
# Gates (pass_to_pass, static)
# ---------------------------------------------------------------------------

# [static] pass_to_pass
def test_syntax_check():
    """Modified files must parse without errors."""
    target = Path(REPO) / ".claude/skills/src/skills/commands/fetch_diff.py"
    r = subprocess.run(
        ["python3", "-c", f"import py_compile; py_compile.compile('{target}', doraise=True)"],
        capture_output=True, text=True, timeout=30,
    )
    assert r.returncode == 0, f"Syntax error in fetch_diff.py:\n{r.stderr}"


# ---------------------------------------------------------------------------
# Fail-to-pass (pr_diff) core behavioral tests
# ---------------------------------------------------------------------------

# [pr_diff] fail_to_pass
def test_deleted_file_included_in_output():
    """Deleted files must appear in filter_diff output instead of being silently dropped."""
    filter_diff = _import_fetch_diff()
    result = filter_diff(DELETED_FILE_DIFF)
    assert "path/to/removed.py" in result, (
        "Deleted file path/to/removed.py should appear in diff output"
    )
    assert "diff --git" in result, "Diff header for deleted file should be present"


# [pr_diff] fail_to_pass
def test_deleted_file_uses_deleted_mask_message():
    """Deleted files must show '[Deleted file - diff masked]' not the auto-generated message."""
    filter_diff = _import_fetch_diff()
    result = filter_diff(DELETED_FILE_DIFF)
    assert "[Deleted file - diff masked]" in result, (
        "Deleted file should use '[Deleted file - diff masked]' mask message"
    )
    assert "[Auto-generated file - diff masked]" not in result, (
        "Deleted file should NOT use the auto-generated mask message"
    )


# [pr_diff] fail_to_pass
def test_deleted_file_pattern_filter():
    """File pattern filtering for deleted files must use the real path (a/ side)."""
    filter_diff = _import_fetch_diff()
    # Filter for *.py should include the deleted .py file
    result_include = filter_diff(MIXED_DIFF, file_patterns=["*.py"])
    assert "path/to/removed.py" in result_include, (
        "Deleted .py file should be included when filtering for *.py"
    )
    # Filter for *.js should exclude it
    result_exclude = filter_diff(MIXED_DIFF, file_patterns=["*.js"])
    assert "path/to/removed.py" not in result_exclude, (
        "Deleted .py file should be excluded when filtering for *.js"
    )


# ---------------------------------------------------------------------------
# Pass-to-pass (pr_diff / static / repo_tests)
# ---------------------------------------------------------------------------

# [repo_tests] pass_to_pass
def test_repo_syntax_check_fetch_diff():
    """fetch_diff.py must have valid Python syntax (pass_to_pass)."""
    target = Path(REPO) / ".claude/skills/src/skills/commands/fetch_diff.py"
    r = subprocess.run(
        ["python3", "-c", f"import py_compile; py_compile.compile('{target}', doraise=True)"],
        capture_output=True, text=True, timeout=30,
    )
    assert r.returncode == 0, f"Syntax error in fetch_diff.py:\n{r.stderr}"


# [repo_tests] pass_to_pass
def test_repo_ast_parse_fetch_diff():
    """fetch_diff.py must parse into valid AST (pass_to_pass)."""
    target = Path(REPO) / ".claude/skills/src/skills/commands/fetch_diff.py"
    r = subprocess.run(
        ["python3", "-c", f"""
import ast
import pathlib
src = pathlib.Path('{target}').read_text()
ast.parse(src)
print('AST parse OK')
"""],
        capture_output=True, text=True, timeout=30,
    )
    assert r.returncode == 0, f"AST parse failed for fetch_diff.py:\n{r.stderr}"


# [repo_tests] pass_to_pass
def test_repo_file_exists_fetch_diff():
    """fetch_diff.py file must exist at expected path (pass_to_pass)."""
    target = Path(REPO) / ".claude/skills/src/skills/commands/fetch_diff.py"
    assert target.exists(), f"fetch_diff.py not found at {target}"
    assert target.is_file(), f"{target} is not a file"


# [repo_tests] pass_to_pass
def test_repo_file_exists_skill_md():
    """SKILL.md file must exist at expected path (pass_to_pass)."""
    target = Path(REPO) / ".claude/skills/fetch-diff/SKILL.md"
    assert target.exists(), f"SKILL.md not found at {target}"
    assert target.is_file(), f"{target} is not a file"


# [pr_diff] pass_to_pass
def test_autogenerated_mask_unchanged():
    """Auto-generated files must still use '[Auto-generated file - diff masked]'."""
    filter_diff = _import_fetch_diff()
    result = filter_diff(AUTOGENERATED_DIFF)
    assert "[Auto-generated file - diff masked]" in result, (
        "Auto-generated files should still use the auto-generated mask message"
    )
    assert "[Deleted file - diff masked]" not in result, (
        "Auto-generated files should NOT use the deleted file mask message"
    )


# [pr_diff] pass_to_pass
def test_regular_file_unaffected():
    """Regular files must still show full diff with line numbers."""
    filter_diff = _import_fetch_diff()
    result = filter_diff(REGULAR_FILE_DIFF)
    assert "+import json" in result, "Regular file additions should appear in output"
    assert "[Deleted file" not in result, "Regular file should not have deleted mask"
    assert "[Auto-generated" not in result, "Regular file should not have auto-gen mask"


# [static] pass_to_pass
def test_not_stub():
    """filter_diff has real logic, not just pass/return."""
    import ast
    src = Path(f"{REPO}/.claude/skills/src/skills/commands/fetch_diff.py").read_text()
    tree = ast.parse(src)
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == "filter_diff":
            body_stmts = [s for s in node.body
                          if not isinstance(s, (ast.Pass, ast.Expr))]
            assert len(body_stmts) >= 5, "filter_diff body is too short to be real"
            return
    raise AssertionError("filter_diff function not found")


# ---------------------------------------------------------------------------
# Config/doc update tests (agentmd-edit)
# ---------------------------------------------------------------------------

# [pr_diff] fail_to_pass
def test_skill_md_documents_deleted_files():
    """SKILL.md must document the deleted file output format."""
    skill_md = Path(REPO) / ".claude/skills/fetch-diff/SKILL.md"
    content = skill_md.read_text()
    assert "Deleted file" in content, (
        "SKILL.md should document deleted file handling"
    )
    assert "dev/null" in content or "/dev/null" in content, (
        "SKILL.md should reference dev/null in the deleted file example"
    )
    assert "[Deleted file - diff masked]" in content, (
        "SKILL.md should show the exact deleted file mask message"
    )
