"""Behavioral checks for pinme-fixpinme-skill-worker-npm (markdown_authoring task).

Each test asserts that a distinctive literal from the gold patch appears
in the target tier-1 file after the agent runs.
"""
from __future__ import annotations

from pathlib import Path

REPO = Path("/workspace/pinme")


def _read(path: str) -> str:
    p = REPO / path
    assert p.is_file(), f"{p} does not exist"
    return p.read_text(encoding="utf-8", errors="replace")


def test_signal_00():
    """Distinctive line from gold patch must be present."""
    text = _read('skills/pinme-api/SKILL.md')
    assert '> `API_KEY` is the sole credential for the Worker to call PinMe platform APIs. When `BASE_URL` is not set, it defaults to `https://pinme.cloud`.' in text, "expected to find: " + '> `API_KEY` is the sole credential for the Worker to call PinMe platform APIs. When `BASE_URL` is not set, it defaults to `https://pinme.cloud`.'[:80]


def test_signal_01():
    """Distinctive line from gold patch must be present."""
    text = _read('skills/pinme-api/SKILL.md')
    assert 'BASE_URL?: string;    // Optional override for PinMe API base URL, defaults to https://pinme.cloud' in text, "expected to find: " + 'BASE_URL?: string;    // Optional override for PinMe API base URL, defaults to https://pinme.cloud'[:80]


def test_signal_02():
    """Distinctive line from gold patch must be present."""
    text = _read('skills/pinme-api/SKILL.md')
    assert "const baseUrl = env.BASE_URL ?? 'https://pinme.cloud';" in text, "expected to find: " + "const baseUrl = env.BASE_URL ?? 'https://pinme.cloud';"[:80]


def test_signal_03():
    """Distinctive line from gold patch must be present."""
    text = _read('skills/pinme/SKILL.md')
    assert 'In this template, the Worker backend is primarily used for JSON APIs. Prefer standard Web APIs and simple manual routing by default. Worker-compatible libraries can be added when needed, but the defau' in text, "expected to find: " + 'In this template, the Worker backend is primarily used for JSON APIs. Prefer standard Web APIs and simple manual routing by default. Worker-compatible libraries can be added when needed, but the defau'[:80]


def test_signal_04():
    """Distinctive line from gold patch must be present."""
    text = _read('skills/pinme/SKILL.md')
    assert '- `pinme.toml`, `backend/wrangler.toml`, and `frontend/.env` are generated by PinMe. Do not edit them manually by default. If extra runtime configuration is truly needed, prefer doing it through PinMe' in text, "expected to find: " + '- `pinme.toml`, `backend/wrangler.toml`, and `frontend/.env` are generated by PinMe. Do not edit them manually by default. If extra runtime configuration is truly needed, prefer doing it through PinMe'[:80]


def test_signal_05():
    """Distinctive line from gold patch must be present."""
    text = _read('skills/pinme/SKILL.md')
    assert '| Node.js capability | Workers now support part of Node.js compatibility, but they are not a full Node.js runtime. Do not assume all Node.js built-in modules are available or behave exactly the same. ' in text, "expected to find: " + '| Node.js capability | Workers now support part of Node.js compatibility, but they are not a full Node.js runtime. Do not assume all Node.js built-in modules are available or behave exactly the same. '[:80]

