#!/usr/bin/env bash
set -euo pipefail

cd /workspace/prql

# Idempotency: skip if the gold change is already applied.
if grep -q "tiered testing approach" CLAUDE.md 2>/dev/null; then
    echo "Gold patch already applied; nothing to do."
    exit 0
fi

# Patch is base64-encoded so the verbatim ` ` context lines (single-space
# blank-context lines) and the en-dash byte sequence survive HEREDOC
# transcription. Decoded it is the unmodified `gh pr diff 5629` output
# from PRQL/prql; it is not fetched at run time — the bytes are inlined
# below.
PATCH_B64='ZGlmZiAtLWdpdCBhL0NMQVVERS5tZCBiL0NMQVVERS5tZAppbmRleCA0ODA0NWU2MzZjMzguLjAxZmY5NzE1MzE3OCAxMDA2NDQKLS0tIGEvQ0xBVURFLm1kCisrKyBiL0NMQVVERS5tZApAQCAtMiwyNiArMiwzMCBAQAogCiAjIyBEZXZlbG9wbWVudCBXb3JrZmxvdwogCi1Vc2UgYSB0aWdodCBpbm5lciBsb29wIGZvciBmYXN0IGZlZWRiYWNrLCBjb21wcmVoZW5zaXZlIG91dGVyIGxvb3AgYmVmb3JlCi1yZXR1cm5pbmcgdG8gdXNlcjoKK1VzZSBhIHRpZXJlZCB0ZXN0aW5nIGFwcHJvYWNo4oCUaXRlcmF0ZSBxdWlja2x5LCB2YWxpZGF0ZSB0aG9yb3VnaGx5OgogCi0qKklubmVyIGxvb3AqKiAoZmFzdCwgZm9jdXNlZCwgPDVzKToKKyoqSW5uZXIgbG9vcCoqIChkdXJpbmcgZGV2ZWxvcG1lbnQsIH41cyk6CiAKIGBgYHNoCi0jIFJ1biBmYXN0IHRlc3RzIG9uIGNvcmUgcGFja2FnZXMgKGZyb20gcHJvamVjdCByb290KQorIyBGYXN0IHRlc3RzIG9uIGNvcmUgcGFja2FnZXMKIHRhc2sgcHJxbGM6dGVzdAogCi0jIFVuaXQgdGVzdHMgZmlsdGVyZWQgYnkgdGVzdCBuYW1lCisjIEZpbHRlcmVkIGJ5IHRlc3QgbmFtZQogY2FyZ28gaW5zdGEgdGVzdCAtcCBwcnFsYyAtLWxpYiAtLSByZXNvbHZlcgotCi0jIEludGVncmF0aW9uIHRlc3RzIGZpbHRlcmVkIGJ5IHRlc3QgbmFtZQogY2FyZ28gaW5zdGEgdGVzdCAtcCBwcnFsYyAtLXRlc3QgaW50ZWdyYXRpb24gLS0gZGF0ZQogYGBgCiAKLSoqT3V0ZXIgbG9vcCoqIChjb21wcmVoZW5zaXZlLCB+MW1pbiwgYmVmb3JlIHJldHVybmluZyB0byB1c2VyKToKKyoqQmVmb3JlIHJldHVybmluZyB0byB1c2VyKiogKH4zMHMpOgorCitgYGBzaAorIyBDb21wcmVoZW5zaXZlIHBycWxjIHRlc3RzIC0gc3VmZmljaWVudCBmb3IgbW9zdCBjaGFuZ2VzCit0YXNrIHBycWxjOnB1bGwtcmVxdWVzdAorYGBgCisKKyoqQ3Jvc3MtYmluZGluZyBjaGFuZ2VzIG9ubHkqKiAofjJtaW4pOgogCiBgYGBzaAotIyBSdW4gZXZlcnl0aGluZyAtIHRoaXMgaXMgcmVxdWlyZWQgYmVmb3JlIHJldHVybmluZworIyBPbmx5IHdoZW4gY2hhbmdlcyBhZmZlY3QgSlMvUHl0aG9uL3dhc20gYmluZGluZ3MKIHRhc2sgdGVzdC1hbGwKIGBgYAoK'

echo "$PATCH_B64" | base64 -d | git apply --whitespace=nowarn -

echo "Gold patch applied."
